### ISSUE TITLE
你好，使用exo播放引擎，Jzvd.reset（）调用后，无法再次播放，7.0.4没有这个问题 

### ISSUE THREAD

**Issue by ksd32767** [Jzvd/JiaoZiVideoPlayer#1]
**什么jzvd版本

**是否和安卓版本有关系，什么版本

**是否和特定品牌的手机机型有关系，什么机型

**相关log是什么

**复现流程

**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
什么log，调用releaseAllVideos什么结果

**Comment by ksd32767** [comment]
> 什么log，调用releaseAllVideos什么结果

调用之后就无法播放了，你可以把播放引擎换成exo测试一下

**Comment by lipangit** [comment]
![image](https://user-images.githubusercontent.com/2038071/71320663-74931e80-24e9-11ea-85c2-e5c8f49912ff.png)

亲测，先点播放exoplayer按钮，然后调用reset函数，视频停止，此时可以通过正常的方式再次播放视频。你的无法播放log是什么。告诉我log这很重要。

**Comment by ksd32767** [comment]
错误日志倒是没发现，你得把播放引擎缓存exoplayer，然后再调用Jzvd.releaseAllVideos();，之后点击播放按钮就不能播放了

**Comment by lipangit** [comment]
用新版
