### ISSUE TITLE
拖动进度条到最后会出现进度回弹

### ISSUE THREAD

**Issue by VincentJ1989** [Jzvd/JiaoZiVideoPlayer#101]
**什么jzvd版本
v7.2.3

**demo是否有这个问题
demo默认展示的那个视频就可以复现

**自己做了哪些修改
无
**如何操作复现
在demo中，把视频拖到最后，可以发现会先反弹到50，再往后播。
项目中我这时长3分10秒左右的会先跳到3分02秒。

**截图或者视频说明情况
![image](https://user-images.githubusercontent.com/16132141/78641109-493f0e80-78e3-11ea-945b-24d2cb1c690b.png)

**Comment by lipangit** [comment]
这是seek进度不准的问题，播放内核有问题，研究一下视频关键帧，需要解决这个问题，你有空能研究一下吗



---原始邮件---
发件人: "Vincent J"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 下午3:21
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 推动进度条到最后会出现进度回弹 (#101)




 
**什么jzvd版本
 v7.2.3
 
**demo是否有这个问题
 demo默认展示的那个视频就可以复现
 
**自己做了哪些修改
 无
 **如何操作复现
 在demo中，把视频拖到最后，可以发现会先反弹到50，再往后播。
 项目中我这时长3分10秒左右的会先跳到3分02秒。
 
**截图或者视频说明情况

**Comment by VincentJ1989** [comment]
音视频这块没怎么接触过：(。还是得依靠大佬们啊。希望有知道咋处理的大佬可以留言哈。

**Comment by ssyRo156** [comment]
![image](https://user-images.githubusercontent.com/18351963/116357557-2c97b080-a82f-11eb-86d1-b47e211a80cd.png)

JZMediaAliyun 播放内核跳帧问题
