### ISSUE TITLE
安装最新版报错

### ISSUE THREAD

**Issue by kivenZheng** [Jzvd/JiaoZiVideoPlayer#103]
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
Show Details
Affected Modules: app

ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
Show Details
Affected Modules: app

**Comment by lipangit** [comment]
亲测这版本能用，检查自己的环境和引用方式



---原始邮件---
发件人: "kivenZheng"<notifications@github.com&gt;
发送时间: 2020年4月7日(周二) 下午5:54
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 安装最新版报错 (#103)




 
ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
 Show Details
 Affected Modules: app
 
ERROR: Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
 Show Details
 Affected Modules: app
 
ERROR: Unable to resolve dependency for ':app@debugUnitTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
 Show Details
 Affected Modules: app
 
ERROR: Unable to resolve dependency for ':app@release/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
 Show Details
 Affected Modules: app
 
ERROR: Unable to resolve dependency for ':app@releaseUnitTest/compileClasspath': Could not resolve cn.jzvd:jiaozivideoplayer:7.2.3.
 Show Details
 Affected Modules: app

**Comment by kivenZheng** [comment]
谢谢
