### ISSUE TITLE
How to disable mobile data warning?

### ISSUE THREAD

**Issue by uzaysan** [Jzvd/JiaoZiVideoPlayer#105]
When using mobile data player show warning .How to disable it?

**Comment by lipangit** [comment]
show me the log

**Comment by Liberations** [comment]
@Override
    public void showWifiDialog() {
        //super.showWifiDialog();
        if (state == STATE_PAUSE) {
            startButton.performClick();
        } else {
            startVideo();
        }
    }

**Comment by uzaysan** [comment]
@Liberations Its working thank you

**Comment by Mayank1904** [comment]
Where to override this method , I am using library dependency so how can I disable this popup

**Comment by lipangit** [comment]
extends jzvdstd override
