### ISSUE TITLE
Remove Logs 

### ISSUE THREAD

**Issue by asadkhanyzi** [Jzvd/JiaoZiVideoPlayer#111]
How to remove logs while playing a video? 
It shows my video url (Private, dont want to disclose it) when I start playing video. 
I already applied proguard rules for my app but it appears that the log is coming from library.
Can you please guide me?

**Comment by lipangit** [comment]
what the log looks like, I did not log the url



---Original---

**Comment by asadkhanyzi** [comment]
it shows info log of mediaplayer while starting a video.
 I/MediaPlayer: setDataSource(https://www.myvideo.com/live.m3u8?a=qcfiihak4nr85usuaugu9596a2)

**Comment by lipangit** [comment]
not jiaozivideoplayer show the url



---Original---
