### ISSUE TITLE
怎么不从第一个视频开始播放

### ISSUE THREAD

**Issue by wpsmgkn** [Jzvd/JiaoZiVideoPlayer#112]
如何不从第一个list开始播放，可以指定第几个

**Comment by lipangit** [comment]
研究一下demo把



---原始邮件---
发件人: "wpsmgkn"<notifications@github.com&gt;
发送时间: 2020年4月13日(周一) 中午11:26
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 怎么不从第一个视频开始播放 (#112)




 
如何不从第一个list开始播放，可以指定第几个
