### ISSUE TITLE
如何取消边存边播，很多直播源都不支持缓存，跟内核无关。

### ISSUE THREAD

**Issue by NanyangTaiji** [Jzvd/JiaoZiVideoPlayer#129]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
研究哪个播放内核支持缓存的设置
