### ISSUE TITLE
cant play .mov videos on samsung devices

### ISSUE THREAD

**Issue by harshakuk** [Jzvd/JiaoZiVideoPlayer#140]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
it depends on mediaplayer core you can change to ijkplayer by singleline code&nbsp; setup(last param)
change to whitch support mov

---Original---

**Comment by harshakuk** [comment]
i tried jzvdStd.setUp(url,"", JzvdStd.SCREEN_NORMAL, JZMediaIjk.class), app is crashing

**Comment by harshakuk** [comment]
Added this to my gradle and it works
    compile 'tv.danmaku.ijk.media:ijkplayer-java:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv7a:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-armv5:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-arm64:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86:0.8.8'
    compile 'tv.danmaku.ijk.media:ijkplayer-x86_64:0.8.8'
