### ISSUE TITLE
如何设置圆角,自定义左上,右上,左下,右下圆角呀

### ISSUE THREAD

**Issue by zhangqifan1** [Jzvd/JiaoZiVideoPlayer#146]
何设置圆角,自定义左上,右上,左下,右下圆角呀,
        int width = view.getWidth();
        int height = view.getHeight();

        outline.setRoundRect(0, 0,width,height,mRadius);
目前使用的 ViewOutlineProvider ,可以统一设置圆角,现在需要自定义各个位置的圆角,请问需要怎么写呀?

**Comment by lipangit** [comment]
jzvd就是个layout，设置这个layout圆角，你多尝试，我没试过，不知道你的处境。

**Comment by zhangqifan1** [comment]
谢谢大佬,我最后用cardview 包起来可以了

**Comment by lipangit** [comment]
兄弟&nbsp; 怎么做的能分享出来吗&nbsp; 放到demo里



---原始邮件---
发件人: "zhangqifan1"<notifications@github.com&gt;
发送时间: 2020年5月20日(周三) 下午5:28
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 如何设置圆角,自定义左上,右上,左下,右下圆角呀 (#146)




 
谢谢大佬,我最后用cardview 包起来可以了
