### ISSUE TITLE
同一个视频多次播放，视频播放不从0开始

### ISSUE THREAD

**Issue by kimiangel** [Jzvd/JiaoZiVideoPlayer#154]
同一个视频多个商品共同播放，退出去换其它的商品播放，视频还是接着上一次结束的时间播放，为什么不是从0开始呀，在ondestory里面调用了jzVideoplayerBanner.releaseAllVideos();没有用，我退出去重新进来还是接着上次结束的位置播放，这是为什么

**Comment by lipangit** [comment]
设置SAVE_PROGRESS=false



---原始邮件---
发件人: "kimiangel"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 上午10:15
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 同一个视频多次播放，视频播放不从0开始 (#154)




 
同一个视频多个商品共同播放，退出去换其它的商品播放，视频还是接着上一次结束的时间播放，为什么不是从0开始呀，在ondestory里面调用了jzVideoplayerBanner.releaseAllVideos();没有用，我退出去重新进来还是接着上次结束的位置播放，这是为什么

**Comment by kimiangel** [comment]
在什么地方设置，我使用的是6.2.12版本，视频控件用的是JZVideoPlayerStandard，我发现没有你说的那个方法SAVE_PROGRESS = false

**Comment by lipangit** [comment]
搜一下，这个变量一直有，可能换地方了



---原始邮件---
发件人: "kimiangel"<notifications@github.com&gt;
发送时间: 2020年5月26日(周二) 下午5:11
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 同一个视频多次播放，视频播放不从0开始 (#154)




 
在什么地方设置，我使用的是6.2.12版本，视频控件用的是JZVideoPlayerStandard，我发现没有你说的那个方法SAVE_PROGRESS = false
