### ISSUE TITLE
列表页滑动出现乱播放视频的问题

### ISSUE THREAD

**Issue by liyuhaolol** [Jzvd/JiaoZiVideoPlayer#162]
**什么jzvd版本
7.4.1
**什么播放器内核
mediaplayer
**相关log是什么
无
**demo是否有这个问题
有
**自己做了哪些修改
我在列表的Recyleiew中使用这个范例，文件为：RecyclerViewActivity，我不希望滑动出屏幕释放掉视频，我想只暂停掉视频。所以做了如下修改，49行开始
```java
if (jzvd != null && Jzvd.CURRENT_JZVD != null && jzvd.jzDataSource.containsTheUrl(Jzvd.CURRENT_JZVD.jzDataSource.getCurrentUrl())) {
                    if (Jzvd.CURRENT_JZVD != null && Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {
                        //Jzvd.releaseAllVideos();
                        Jzvd.goOnPlayOnPause();
                    }
                }
```
**如何操作复现
点击开始播放第一个视频（为了演示，第几个视频都一样，前提是数量够），手动暂停或者不手动暂停都可以，向下滑动。按照我的理解，第一个视频移出屏幕后，应该暂停。事实上也是这样的。但是不知道为什么，当position+8的视频显示出来时，框架会自动播放那个视频。开始我是引用的框架，自己写demo发现有这个问题，后续下载官方的demo，发现也有这个问题。代码完全是按照范例来写的，并没有做什么自定义修改。所以怀疑是框架的问题。
**什么安卓版本，什么机型
目前测试了Android10，Android8.1，小米9，魅族16X，和一堆虚拟机全部都是一模一样的问题。
**截图或者视频说明情况
这个问题不光能在“RECYLEVIEW中使用”复现，在“普通LISTVIEW用法”也可以复现，相对概率低。“RECYLEVIEW中使用”中几乎100% 复现。请问我是不应该在滑动中使用Jzvd.goOnPlayOnPause();这个方法么？
感觉这个问题像是触发了滑动自动播放的逻辑。但是我无法确认具体问题。如果我不应该在滑动中调用Jzvd.goOnPlayOnPause();，那我应该如何仅仅暂停视频呢？
这是我的小米9录屏，请您过目：https://weibo.com/tv/v/J5YETgtZx

**Comment by lipangit** [comment]
这个需求有点复杂，因为列表被复用，textureview已经不是原来的了，并且需要新生成textureview



---原始邮件---
发件人: "liyuhao"<notifications@github.com&gt;
发送时间: 2020年6月10日(周三) 中午12:59
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 列表页滑动出现乱播放视频的问题 (#162)




 
**什么jzvd版本
 7.4.1
 **什么播放器内核
 mediaplayer
 **相关log是什么
 无
 **demo是否有这个问题
 有
 **自己做了哪些修改
 我在列表的Recyleiew中使用这个范例，文件为：RecyclerViewActivity，我不希望滑动出屏幕释放掉视频，我想只暂停掉视频。所以做了如下修改，49行开始
 if (jzvd != null &amp;&amp; Jzvd.CURRENT_JZVD != null &amp;&amp; jzvd.jzDataSource.containsTheUrl(Jzvd.CURRENT_JZVD.jzDataSource.getCurrentUrl())) {                     if (Jzvd.CURRENT_JZVD != null &amp;&amp; Jzvd.CURRENT_JZVD.screen != Jzvd.SCREEN_FULLSCREEN) {                         //Jzvd.releaseAllVideos();                         Jzvd.goOnPlayOnPause();                     }                 }
 
**如何操作复现
 点击开始播放第一个视频（为了演示，第几个视频都一样，前提是数量够），手动暂停或者不手动暂停都可以，向下滑动。按照我的理解，第一个视频移出屏幕后，应该暂停。事实上也是这样的。但是不知道为什么，当position+8的视频显示出来时，框架会自动播放那个视频。开始我是引用的框架，自己写demo发现有这个问题，后续下载官方的demo，发现也有这个问题。代码完全是按照范例来写的，并没有做什么自定义修改。所以怀疑是框架的问题。
 **什么安卓版本，什么机型
 目前测试了Android10，Android8.1，小米9，魅族16X，和一堆虚拟机全部都是一模一样的问题。
 **截图或者视频说明情况
 这个问题不光能在“RECYLEVIEW中使用”复现，在“普通LISTVIEW用法”也可以复现，相对概率低。“RECYLEVIEW中使用”中几乎100% 复现。请问我是不应该在滑动中使用Jzvd.goOnPlayOnPause();这个方法么？
 感觉这个问题像是触发了滑动自动播放的逻辑。但是我无法确认具体问题。如果我不应该在滑动中调用Jzvd.goOnPlayOnPause();，那我应该如何仅仅暂停视频呢？
 这是我的小米9录屏，请您过目：https://weibo.com/tv/v/J5YETgtZx

**Comment by liyuhaolol** [comment]
了解了，是我疏忽了复用的问题，已经改成释放视频的逻辑。

**Comment by lipangit** [comment]
么么哒



---原始邮件---
发件人: "liyuhao"<notifications@github.com&gt;
发送时间: 2020年6月14日(周日) 下午2:40
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 列表页滑动出现乱播放视频的问题 (#162)




 
Closed #162.
