### ISSUE TITLE
Ijk播放视频，onProgress()监听，视频暂停之后点击继续播放， position 不对

### ISSUE THREAD

**Issue by walkingCoder** [Jzvd/JiaoZiVideoPlayer#174]
**什么jzvd版本
7.4.2
**什么播放器内核
ijk
**相关log是什么

**demo是否有这个问题
是
**自己做了哪些修改
无
**如何操作复现
用ijk内核播放视频，打印onProgress日志， 视频播放- 暂停播放-点击继续播放
**什么安卓版本，什么机型
9.0   小米6
**截图或者视频说明情况
暂停播放之后，点击继续播放。 onProgress() 日志 position不对。
![image](https://user-images.githubusercontent.com/10471876/84997581-5bf67f00-b181-11ea-896f-1fab6dfef76b.png)

**Comment by lipangit** [comment]
效果上有没有异常

**Comment by walkingCoder** [comment]
@lipangit 效果上没有异常，但是 我的业务逻辑需要监听视频播放进度，做一些事情，这样的话，进度就不正确了，业务的状态就不对了。

**Comment by lipangit** [comment]
红框内是currenttime，你看界面上转换成时分秒有异常吗。

可以更换播放内核，他是播放内核传过来的。

**Comment by walkingCoder** [comment]
是，ijkplayer内核传过来的position。 那就没招了~~
