### ISSUE TITLE
Can i remove the popup while starting the video on mobile network

### ISSUE THREAD

**Issue by Mayank1904** [Jzvd/JiaoZiVideoPlayer#178]
([url](url
![processed](https://user-images.githubusercontent.com/16149915/85397814-dd7b5200-b571-11ea-8f31-b129f940ac3c.jpeg)
))

I need to remove the popup when starting the video with autoPlay condition

**Comment by minzbox** [comment]
Check isWifiConnected() method in JZUtils.java

**Comment by Mayank1904** [comment]
this method will check wifi connected or not 
but i need to play the video on mobile network but withod the above warning

**Comment by Liberations** [comment]
> this method will check wifi connected or not
> but i need to play the video on mobile network but withod the above warning
> 
> binding.root.feedVideoPlayerLayout.setUp(
> proxy.getProxyUrl(data.videoUrl), ""
> , JzvdStd.SCREEN_NORMAL
> )
> 
> I am using the above code to setup the video thumbnail in recyclerview item
> 
> So what code should I change to remove the above warning popup

Extend jzvdStd and override method

**Comment by Mayank1904** [comment]
Not understanding what you want to say, please elaborate your answer or can you give me the code example

**Comment by minzbox** [comment]
This method check wifi connect, if true dialog will not show, if false, it means you are using 3G/4G. The easiest way is remove/not using this method.

**Comment by Liberations** [comment]
#105 
`public class MyJzvd extends JzvdStd {
    public MyJzvd(Context context) {
        super(context);
    }

    public MyJzvd(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void showWifiDialog() {
        //super.showWifiDialog();
        if (state == STATE_PAUSE) {
            startButton.performClick();
        } else {
            startVideo();
        }
    }
}`

**Comment by Mayank1904** [comment]
But how to use this?

in xml

<cn.jzvd.JzvdStd
                                    android:id="@+id/feedVideoPlayerLayout"
                                    android:layout_width="match_parent"
                                    android:layout_height="match_parent"
                                    android:layout_marginEnd="0dp"
                                    android:layout_marginStart="0dp"
                                    android:layout_marginTop="0dp"/>

in code 

feedVideoPlayerLayout.setUp(
                        proxy.getProxyUrl(data.videoUrl), ""
                        , JzvdStd.SCREEN_NORMAL
                    )

Where to override this

Please help me

**Comment by lipangit** [comment]
learn from demo please.



---Original---

**Comment by Mayank1904** [comment]
I dont see any Custom JZvd class in demo to learn

**Comment by lucazin** [comment]
Its possible to change color of this message?

the color of text here is white.. and background is white too ..so i cant see nothing.

**Comment by lucazin** [comment]
how i can override this method?

**Comment by lipangit** [comment]
liberation's answer is right it is a standard sulotion . please study his code. it will solve your question
