### ISSUE TITLE
只把库引进gradle后，安装就报错，求助

### ISSUE THREAD

**Issue by rooney0928** [Jzvd/JiaoZiVideoPlayer#18]
**什么jzvd版本
7.0.5
**相关log是什么
 java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.lyc.player/com.lyc.player.ui.activity.SplashActivity}: java.lang.ClassNotFoundException: Didn't find class "com.lyc.player.ui.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/com.lyc.player-GRewxizQR5yKctqqjYrhqA==/base.apk"]

 Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lyc.player.ui.activity.SplashActivity" on path: DexPathList[[zip file "/data/app/com.lyc.player-GRewxizQR5yKctqqjYrhqA==/base.apk"],nativeLibraryDirectories=[/data/app/com.lyc.player-GRewxizQR5yKctqqjYrhqA==/lib/arm64, /system/lib64, /system/vendor/lib64]]

//只加了implementation 'cn.jzvd:jiaozivideoplayer:7.0.5'

大致就是不能打开原来的闪屏页面(也就是启动页面)，本来可以

**demo是否有这个问题
毫无问题
**如何操作复现
https://gitee.com/wayne0928/myvideo
直接安装会报错

**什么安卓版本，什么机型
android8.0 
三星s7国行
**最好有截图或者视频说明情况
部署好直接就是"xxx已停止",具体情况就这些

老哥麻烦看下，谢了

**Comment by lipangit** [comment]
gitee的链接无法打开403无权限。是不是引入了ijkplayer，找不到so。

**Comment by rooney0928** [comment]
> gitee的链接无法打开403无权限。是不是引入了ijkplayer，找不到so引发闪退，log里没有jzvd的字样。

过滤了一下，没有jzvd的痕迹

打不开的话，那个工程直接发你邮箱吧

**Comment by rooney0928** [comment]
> gitee的链接无法打开403无权限。是不是引入了ijkplayer，找不到so引发闪退，log里没有jzvd的字样。

找到原因了，需要在gradle的android下加这些引用
`
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
`

**Comment by lipangit** [comment]
ok
