### ISSUE TITLE
文档和demo 很多地方不对应差别很大

### ISSUE THREAD

**Issue by yuzhongrong** [Jzvd/JiaoZiVideoPlayer#186]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by yuzhongrong** [comment]
比如说 Jzvd.setMediaInterface(new JZMediaIjkplayer());  //  ijkMediaPlayer  这句话 切换内核 但是呢 demo中是Jzvdstd 
并且demo中没有JZMediaIjkplayer 这个类  demo中猜测应该是JZMediaIjk  然后呢 这个JZMediaIjk 的构造方法传的是一个Jzvd 简直是奇葩了 怎么能传Jzvd呢

**Comment by yuzhongrong** [comment]
var jzvdStd=JzvdStd(this)
     jzvdStd.setMediaInterface(JZMediaIjk(jzvdStd))

我是真么写的 是没有错了  jzvdstd 继承了jzvd  有错吗

**Comment by yuzhongrong** [comment]
你那个JZmediaIjk（Jzvd  jzvd）传的是Jzvd方法我这样写有什么错 请问

**Comment by yuzhongrong** [comment]
[完整代码](http://note.youdao.com/s/M9wkv5DB)

**Comment by yuzhongrong** [comment]
videoplayer.setMediaInterface(JZMediaIjk::class.java)  这样子写是可以的

**Comment by lipangit** [comment]
以demo为主
