### ISSUE TITLE
饺子播放器是否对在线视频文件大小有限制？

### ISSUE THREAD

**Issue by crazeluo** [Jzvd/JiaoZiVideoPlayer#19]
敬爱的作者大大，项目引入饺子播放器，播放在线视频超过100M就会一直转圈圈,这种该怎么处理？

**Comment by lipangit** [comment]
用的哪个播放内核，三种常用的都试试

**Comment by crazeluo** [comment]
> 
> 
> 用的哪个播放内核，三种常用的都试试

我没有设置，是用的默认的，我试下其他的，感谢！！

**Comment by crazeluo** [comment]
![图片](https://user-images.githubusercontent.com/22833632/71437436-b233b980-272c-11ea-8b02-e4e57374215f.png)
根据文档，在demo里没找到这两个类啊
