### ISSUE TITLE
合理提出issue，送JZT

### ISSUE THREAD

**Issue by lipangit** [Jzvd/JiaoZiVideoPlayer#26]
合理提出issue，解答后提出者送2000JZT。

**Comment by robotxia2095** [comment]
饺子播放器在快进的时候,一个60分钟的视频,轻轻一划就过去十几分钟到几十分钟,用户本来想快进几十秒或者几分钟,所以提出给开发者添加一个滑动系数来根据实际需求去控制快进或快退的的时间数,以方便开发者开发的时候更方便,播放器更完善

**Comment by lipangit** [comment]
ok提交pr



---原始邮件---
发件人: "robotxia2095"<notifications@github.com&gt;
发送时间: 2020年3月24日(周二) 下午5:45
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Nathen"<1066666651@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 合理提出issue，送JZT (#26)




 
饺子播放器在快进的时候,一个60分钟的视频,轻轻一划就过去十几分钟到几十分钟,用户本来想快进几十秒或者几分钟,所以提出给开发者添加一个滑动系数来根据实际需求去控制快进或快退的的时间数,以方便开发者开发的时候更方便,播放器更完善

**Comment by leopku** [comment]
遇到同样的问题
轻轻一划，快速或后退的太多，求解决方案

**Comment by lipangit** [comment]
@robotxia2095 这个问题已经计划很久了，有空系统的研究一下怎么处理吗
