### ISSUE TITLE
切换清晰度后无法正常播放

### ISSUE THREAD

**Issue by tony1088** [Jzvd/JiaoZiVideoPlayer#28]
**什么jzvd版本
7.0.5  7.1.0  ---Demo
**相关log是什么
12-25 16:07:58.903 751-20361/? I/NuPlayer: performReset
12-25 16:07:58.903 751-20361/? I/NuPlayer: performReset: mRendererLooper->stop()
12-25 16:07:58.903 751-20361/? I/NuPlayer: performReset: mSource->stop()
12-25 16:07:58.903 751-20361/? I/GenericSource: stop()
12-25 16:07:58.903 19656-20424/cn.jzvd.demo W/MediaPlayer: setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
12-25 16:07:58.905 751-1803/? I/NuPlayerDriver: setDataSource(0xf1d695e0) url(http://jzvd.nathen.cn/f07fa9fddd1e45a6ae1570c7fe7967c1/c6db82685b894e25b523b1cb28d79f2e-5287d2089db37e62345123a1be272f8b.mp4)
12-25 16:07:58.905 751-20361/? I/NuPlayer: performReset completed!
12-25 16:07:58.905 751-1803/? I/ExtendedGenericSource: CreatePersistentSource uid 10105 url http://jzvd.nathen.cn/f07fa9fddd1e45a6ae1570c7fe7967c1/c6db82685b894e25b523b1cb28d79f2e-5287d2089db37e62345123a1be272f8b.mp4
12-25 16:07:58.906 751-1803/? I/ExtendedGenericSource: Persistent source creation is disabled by property
12-25 16:07:58.906 751-1803/? I/NuPlayerDriver: setDataSource(url) wait mLock
12-25 16:07:58.906 751-751/? I/NuPlayerDriver: reset(mState = 0) get mLock
12-25 16:07:58.906 751-751/? I/NuPlayerDriver: ~NuPlayerDriver(0xf1d693a0)
12-25 16:07:58.906 751-20425/? I/NuPlayerDriver: notifySetDataSourceCompleted err = 0
12-25 16:07:58.906 751-751/? I/NuPlayerDriver: ~NuPlayerDriver(0xf1d693a0) end
12-25 16:07:58.906 751-1803/? I/NuPlayerDriver: setDataSource(url) get mLock
12-25 16:07:58.907 751-1803/? I/NuPlayerDriver: prepareAsync(0xf1d695e0)
12-25 16:07:58.907 19656-20424/cn.jzvd.demo W/System.err: java.lang.IllegalArgumentException: surfaceTexture must not be null
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at android.view.Surface.<init>(Surface.java:140)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at cn.jzvd.JZMediaSystem.lambda$prepare$0$JZMediaSystem(JZMediaSystem.java:53)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at cn.jzvd.-$$Lambda$JZMediaSystem$1SfpWnrQJjBakrZ3K2nGWWoyock.run(lambda)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at android.os.Handler.handleCallback(Handler.java:739)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at android.os.Looper.loop(Looper.java:179)
12-25 16:07:58.908 19656-20424/cn.jzvd.demo W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)
**demo是否有这个问题
demo 7.0.5 , 7.1.0 ，切换清晰度后都无法正常播放
**如何操作复现
demo 必现
**什么安卓版本，什么机型
oppoR9S   小米8
**最好有截图或者视频说明情况

**Comment by lipangit** [comment]
用新版
