### ISSUE TITLE
Fragment shows when click fullscreen button

### ISSUE THREAD

**Issue by cemalsayin** [Jzvd/JiaoZiVideoPlayer#298]
Hi i use JzvdStd videoView in my activity however  i called  show videoView metod in fragment. That Fragment in activity and i call it in  getSupportFragmentManager  fragment container with BottomNavigationView. My problem is when i click fullscreen button fragment rotate with view and i can't see fullscreen videoView. I guess i must close or hide fragment when click fullscreen button but i can't find any way. Could you help me please?

**Comment by lipangit** [comment]
Can you show me the plromblem in demo I will debug for you.



---Original---

**Comment by cemalsayin** [comment]
Hi @lipangit,  It'a little bit complicated but i'll try explain it; by the way thanks for your attention

I use [draggablePanel](https://github.com/pedrovgs/DraggablePanel) for make a draggable video player view like youtube app which view connected my mainActivity. Main Activity has include BottomNavigationView and FrameLayout. I'm showing my fragments with these structure. When i click show video button for open video view metod in fragment, draggable view shows and play video with JzvdStd. Eveything works as well that point however when i click JzvdStd's fullscreen button draggable view and JzvdStd disappear also previous fragment show which has show video button. I shared screen shoots first image my player view when i click fullscreen button second ss comes which is a fragment and i'm calling video player view in there. 

![Screenshot_1609532394](https://user-images.githubusercontent.com/35407261/103445973-5f6bd680-4c8b-11eb-9de7-fa5a66117719.png)

![Screenshot_1609533535](https://user-images.githubusercontent.com/35407261/103445977-67c41180-4c8b-11eb-8aab-9d2b490db46b.png)
