### ISSUE TITLE
关于BottomProgressBar手动隐藏后，再次显示的问题

### ISSUE THREAD

**Issue by ZhaoYidong** [Jzvd/JiaoZiVideoPlayer#299]
**什么jzvd版本：7.5.0

**什么播放器内核：默认

**相关log是什么

**demo是否有这个问题：Demo 中列表都是默认显示底部进度条，没有这个需求

**自己做了哪些修改：
    @Override
    public void setAllControlsVisiblity(int topCon, int bottomCon, int startBtn, int loadingPro, int posterImg, int bottomPro, int retryLayout) {
        super.setAllControlsVisiblity(topCon, bottomCon, startBtn, loadingPro, posterImg, bottomPro, retryLayout);
        topContainer.setVisibility(GONE);
        bottomContainer.setVisibility(GONE);
        startButton.setVisibility(startBtn);
        loadingProgressBar.setVisibility(loadingPro);
        posterImageView.setVisibility(GONE);
        bottomProgressBar.setVisibility(GONE);
        mRetryLayout.setVisibility(GONE);
    }

**如何操作复现
点击视频任意位置，暂停按钮悬浮，等待暂停按钮小时，底部进度条就出现了，但进度不更新。
    public void dissmissControlView() {
        if (state != STATE_NORMAL
                && state != STATE_ERROR
                && state != STATE_AUTO_COMPLETE) {
            post(() -> {
                bottomContainer.setVisibility(View.INVISIBLE);
                topContainer.setVisibility(View.INVISIBLE);
                startButton.setVisibility(View.INVISIBLE);

                if (screen != SCREEN_TINY) {
                    bottomProgressBar.setVisibility(View.VISIBLE);
                }
                cancelProgressTimer();
            });
        }
    }
可能是这个代码导致的

**什么安卓版本，什么机型
Pixel 3 XL

**截图或者视频说明情况

**Comment by ZhaoYidong** [comment]
提完问题就知道答案了。
我实现了dissmissControlView，将有问题的代码注释掉就 ok 了
    @Override
    public void dissmissControlView() {
        if (state != STATE_NORMAL
                && state != STATE_ERROR
                && state != STATE_AUTO_COMPLETE) {
            post(() -> {
                bottomContainer.setVisibility(View.INVISIBLE);
                topContainer.setVisibility(View.INVISIBLE);
                startButton.setVisibility(View.INVISIBLE);
//                if (screen != SCREEN_TINY) {
//                    bottomProgressBar.setVisibility(View.VISIBLE);
//                }
                cancelProgressTimer();
            });
        }
    }

**Comment by lipangit** [comment]
Ok
