### ISSUE TITLE
Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.setSpeed(float)' on a null object reference

### ISSUE THREAD

**Issue by LeSwp** [Jzvd/JiaoZiVideoPlayer#300]
**什么jzvd版本
最新版本
**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
加入控件判空
**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
需要更多信息



---Original---
