### ISSUE TITLE
大佬，ijk播放器播放m3u8直播流一会儿会画面卡住，没声音也没有任何log或者error打印。exo不会 

### ISSUE THREAD

**Issue by xuzh2017** [Jzvd/JiaoZiVideoPlayer#303]
如题

**Comment by lipangit** [comment]
超出本裤解决范围



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2021年1月6日(周三) 晚上7:53
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 大佬，ijk播放器播放m3u8直播流一会儿会画面卡住，没声音也没有任何log或者error打印。exo不会  (#303)




 
如题
