### ISSUE TITLE
使用startFullscreenDirectly全屏播放视频返回原界面，本来隐藏的状态栏会显示出来

### ISSUE THREAD

**Issue by uHone** [Jzvd/JiaoZiVideoPlayer#304]
**什么jzvd版本
7.6.0

**什么播放器内核
默认
**相关log是什么
无
**demo是否有这个问题
有
**自己做了哪些修改
activity横屏，隐藏状态栏
**如何操作复现
1.将demo 中DirectPlayActivity改为横屏   android:screenOrientation="landscape"
2.隐藏状态栏 getWindow().setFlags(WindowManager.LayoutParams.FLAG_FULLSCREEN, WindowManager.LayoutParams.FLAG_FULLSCREEN);
3.全屏播放视频再返回，已隐藏的状态栏就会再出现
**什么安卓版本，什么机型
任何
**截图或者视频说明情况

**Comment by Liberations** [comment]
onCreate中调用 JZUtils.hideSystemUI(this); 

onResume固定横屏

  @Override
    protected void onResume() {
        super.onResume();
        Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
        Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;
    }

**Comment by uHone** [comment]
> onCreate中调用JZUtils.hideSystemUI（this）;
> 
> onResume固定横屏
> 
> @override
> protected void onResume（）{
> super.onResume（）;
> Jzvd.FULLSCREEN_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE;
> Jzvd.NORMAL_ORIENTATION = ActivityInfo.SCREEN_ORIENTATION_SENSOR_LANDSCAPE;
> }

非常感谢
