### ISSUE TITLE
在沉浸式状态下，使用自己的数据流量，在自动播放的时候弹出的流量提示的dialog会改变状态栏颜色

### ISSUE THREAD

**Issue by ZHUHUOHUO** [Jzvd/JiaoZiVideoPlayer#309]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by lipangit** [comment]
继承jzvdstd复写某个带dialog的函数(名字忘记了)可以自定义弹出来的对话框，不需要也可以屏蔽 不弹对话框



---原始邮件---
发件人: "ZHUHUOHUO"<notifications@github.com&gt;
发送时间: 2021年1月16日(周六) 下午3:38
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 在沉浸式状态下，使用自己的数据流量，在自动播放的时候弹出的流量提示的dialog会改变状态栏颜色 (#309)




 
**什么jzvd版本
 
**什么播放器内核
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by Liberations** [comment]
重写 showWifiDialog()
