### ISSUE TITLE
如何关闭播放器在RecyclerView上的自动播放功能

### ISSUE THREAD

**Issue by Liyize97126** [Jzvd/JiaoZiVideoPlayer#311]
**您好，我想问一下这个播放器有没有关闭关闭播放器在RecyclerView上的自动播放功能，如果有，那问下怎样做才可以实现这一功能，谢谢。

**Comment by Liberations** [comment]
默认情况下是不会自动播放的，你参考下demo

**Comment by Liyize97126** [comment]
好的，我回头看一下，谢谢啦
