### ISSUE TITLE
在4.4版本机顶盒上，出现画面变蓝色的情况，帮忙看一下

### ISSUE THREAD

**Issue by lzy2626** [Jzvd/JiaoZiVideoPlayer#312]
**什么jzvd版本
最新版本
**什么播放器内核
所有内核
**相关log是什么
没有log
**demo是否有这个问题
是
**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型
机顶盒 4.4  创维盒子
**截图或者视频说明情况
![image](https://user-images.githubusercontent.com/11204711/105474529-44641380-5cd9-11eb-8653-3ea3a0d5c364.png)

**Comment by lipangit** [comment]
新建项目 用mediaplayer和textureview试试&nbsp;



---原始邮件---
发件人: "liuzhanyue"<notifications@github.com&gt;
发送时间: 2021年1月22日(周五) 下午5:44
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 在4.4版本机顶盒上，出现画面变蓝色的情况，帮忙看一下 (#312)




 
**什么jzvd版本
 最新版本
 **什么播放器内核
 所有内核
 **相关log是什么
 没有log
 **demo是否有这个问题
 是
 **自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 机顶盒 4.4  创维盒子
 **截图或者视频说明情况
