### ISSUE TITLE
7.6.0 API需求 and Bug

### ISSUE THREAD

**Issue by ztind** [Jzvd/JiaoZiVideoPlayer#314]
**需求描述
1.希望添加视频播放vs暂停的回掉监听处理接口，用于ui刷新或其他UI处理
2.seekTo(position)，跳转到指定位置播放这个api好像没有了，希望加上
3. 希望添加监听视频进度条拖动播放的回掉，代码里的jzVideo.progressBar.setOnSeekBarChangeListener()这个方法我试过了貌似无效，而且视频进度还不会跟着走

**Comment by lipangit** [comment]
1 onstate...函数可以取得视频的回调
2用mediainterface.seekto&nbsp; 操作mediaplayer
3progressbar设置操作监听应该没错。因为有线程在不停的刷新进度



---原始邮件---
发件人: "ZT"<notifications@github.com&gt;
发送时间: 2021年1月24日(周日) 凌晨4:28
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 7.6.0 API需求 and Bug (#314)




 
**需求描述
 1.希望添加视频播放vs暂停的回掉监听处理接口，用于ui刷新或其他UI处理
 2.seekTo(position)，跳转到指定位置播放这个api好像没有了，希望加上
 3. 希望添加监听视频进度条拖动播放的回掉，代码里的jzVideo.progressBar.setOnSeekBarChangeListener()这个方法我试过了貌似无效，而且视频进度还不会跟着走

**Comment by ztind** [comment]
> 1 onstate...函数可以取得视频的回调 2用mediainterface.seekto&nbsp; 操作mediaplayer 3progressbar设置操作监听应该没错。因为有线程在不停的刷新进度
> […](#)
> ---原始邮件--- 发件人: "ZT"<notifications@github.com&gt; 发送时间: 2021年1月24日(周日) 凌晨4:28 收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JZVideo] 7.6.0 API需求 and Bug (#314) **需求描述 1.希望添加视频播放vs暂停的回掉监听处理接口，用于ui刷新或其他UI处理 2.seekTo(position)，跳转到指定位置播放这个api好像没有了，希望加上 3. 希望添加监听视频进度条拖动播放的回掉，代码里的jzVideo.progressBar.setOnSeekBarChangeListener()这个方法我试过了貌似无效，而且视频进度还不会跟着走 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

1.这个是需要自定义播放器的吧，即继承JzvdStd
2.jzVideo.progressBar.setOnSeekBarChangeListener() 这个api，拖动进度条视频快进失败，有bug

**Comment by lipangit** [comment]
对  


Bug什么log

**Comment by ztind** [comment]
> 对
> 
> Bug什么log

调用了jzVideo.progressBar.setOnSeekBarChangeListener() 这个方法后，拖动进度条视频快进失败。

**Comment by Liberations** [comment]
setOnSeekBarChangeListener会覆盖jzvd原有的逻辑。监听进度这里建议复写onProgress方法
