### ISSUE TITLE
拖动进度条后，视频加载到进度条位置，视频开始播放，可是左边的时间会停留4秒左右才会变化

### ISSUE THREAD

**Issue by yxnxiao** [Jzvd/JiaoZiVideoPlayer#315]
**什么jzvd版本
cn.jzvd:jiaozivideoplayer:7.6.0
我下载demo的apk，也是有这个问题
**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by kezhian** [comment]
public void onProgress(int progress, long position, long duration) {
        Log.d(TAG, "onProgress: progress=" + progress + " position=" + position + " duration=" + duration);
        mCurrentPosition = position;
        if (!mTouchingProgressBar) {
            if (seekToManulPosition != -1) {
                if (seekToManulPosition > progress) {
                    Log.e(TAG, "seekToManulPosition:"+seekToManulPosition+" > progress:"+progress+",不执行onProgress");
                    return;
                } else {
                    seekToManulPosition = -1;//这个关键帧有没有必要做
                }
            } else {
                if (progress != 0) progressBar.setProgress(progress);
            }
        }
        if (position != 0) currentTimeTextView.setText(JZUtils.stringForTime(position));
        totalTimeTextView.setText(JZUtils.stringForTime(duration));
    }

主要是视频的关键帧太少了，作者在这里添加了seekToManulPosition参数，用以控制，所以会导致停顿几秒（关键帧问题解决办法太少）；
你可以去掉seekToManulPosition的逻辑，但是seekbar游标和currentTimeTextView会回跳几秒

**Comment by lipangit** [comment]
播放进度不准，和视频的关键帧有关系



---原始邮件---
发件人: "yxnxiao"<notifications@github.com&gt;
发送时间: 2021年1月25日(周一) 上午10:32
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] 拖动进度条后，视频加载到进度条位置，视频开始播放，可是左边的时间会停留4秒左右才会变化 (#315)




 
**什么jzvd版本
 cn.jzvd:jiaozivideoplayer:7.6.0
 我下载demo的apk，也是有这个问题
 **什么播放器内核
 
**相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 
**如何操作复现
 
**什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by lipangit** [comment]
有没有办法给视频添加关键帧

**Comment by yilylong** [comment]
确实拖动进图条实际seek到位置和进度条不一致有闪回 加上关键帧判断 又导致拖动完成后 延迟更新的感觉
