### ISSUE TITLE
自定义播放内核界面 ，替换原视频，切换内核遇到的问题

### ISSUE THREAD

**Issue by gwwl** [Jzvd/JiaoZiVideoPlayer#316]
**什么jzvd版本
7.6.0
**什么播放器内核
JZMediaExo
**相关log是什么

**demo是否有这个问题
有，是自定义播放内核界面，切换为JZMediaExo内核后
**自己做了哪些修改
替换了视频链接，替不替换都有这个问题
**如何操作复现
暂停视频后，拉动滚动条，一直转圈圈，不暂停没事
**什么安卓版本，什么机型
Android  10  华为荣耀10
**截图或者视频说明情况
更换视频链接：
http://stream.iqilu.com/vod_bag_2016//2020/02/16/903BE158056C44fcA9524B118A5BF230/903BE158056C44fcA9524B118A5BF230_H264_mp4_500K.mp4

都是 自定义播放内核界面问题
2.还有个问题，修改JZMediaIjk的如下配置将大小改小后，会出现进度条闪烁隐藏和显示
 //最大缓冲大小,单位kb
ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_PLAYER, "max-buffer-size", 1024 * 10);
//播放前的探测Size，默认是1M, 改小一点会出画面更快
 ijkMediaPlayer.setOption(IjkMediaPlayer.OPT_CATEGORY_FORMAT, "probesize", 1024 * 2);

3.这个JZMediaIjk，暂停情况下如何把暂停画面变为进度条的位置画面。而不是原先位置的画面

**Comment by gwwl** [comment]
使用JZMediaSystem内核没啥问题

**Comment by lipangit** [comment]
用的哪个jzvd版本使用对应的jzexo内核

Loading的圈现实与否断点一下，哪个函数操作了loading

3是什么意思

**Comment by Liberations** [comment]
这个JZMediaIjk，暂停情况下如何把暂停画面变为进度条的位置画面。而不是原先位置的画面 ，延迟较大

**Comment by caozhen456521** [comment]
在seekTo里面加            JZUtils.saveProgress(jzvd.getContext(),jzvd.jzDataSource.getCurrentUrl().toString(), time);
            simpleExoPlayer.play();
