### ISSUE TITLE
startPreloading直接播放??

### ISSUE THREAD

**Issue by zwping** [Jzvd/JiaoZiVideoPlayer#317]
jzvd: 7.6.0
exo: 2.12.3

---

startPreloading方法理解为开始预加载？但实际调用的时候jzvd直接播放了

```kotlin
jzvd.setUp("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", "", Jzvd.SCREEN_NORMAL, JZMediaExo::class.java)
jzvd.startPreloading()
```

**Comment by zwping** [comment]
严格按照[Demo](https://github.com/Jzvd/JZVideo/blob/develop/demo/src/main/java/cn/jzvd/demo/Tab_1_Basic/PreloadingActivity.java)来，更换ijk内核

**Comment by lipangit** [comment]
Demo有这问题吗



---原始邮件---
发件人: "詹"<notifications@github.com&gt;
发送时间: 2021年1月25日(周一) 中午1:41
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] startPreloading直接播放?? (#317)




 
jzvd: 7.6.0
 exo: 2.12.3
 
 
startPreloading方法理解为开始预加载？但实际调用的时候jzvd直接播放了
 jzvd.setUp("http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4", "", Jzvd.SCREEN_NORMAL, JZMediaExo::class.java) jzvd.startPreloading()
