### ISSUE TITLE
onStatePause 方法有问题

### ISSUE THREAD

**Issue by smartbackme** [Jzvd/JiaoZiVideoPlayer#318]
public void onStatePause() {
        Log.i(TAG, "onStatePause " + " [" + this.hashCode() + "] ");
        state = STATE_PAUSE;
        startProgressTimer();
    }

应该用 cancelProgressTimer(); 吧

**Comment by lipangit** [comment]
忘记了为什么这么写，有什么症状吗现在



---原始邮件---
发件人: "zhonghua"<notifications@github.com&gt;
发送时间: 2021年1月25日(周一) 下午3:47
收件人: "Jzvd/JZVideo"<JZVideo@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JZVideo] onStatePause 方法有问题 (#318)




 
public void onStatePause() {
 Log.i(TAG, "onStatePause " + " [" + this.hashCode() + "] ");
 state = STATE_PAUSE;
 startProgressTimer();
 }
 
应该用 cancelProgressTimer(); 吧

**Comment by Liberations** [comment]
目前看 STATE_PLAYING STATE_PAUSE STATE_PREPARING_PLAYING都会继续保持更新progress
