### ISSUE TITLE
很容易出现Jzvd.mediaInterfaceClass为null的现象

### ISSUE THREAD

**Issue by forrest-x** [Jzvd/JiaoZiVideoPlayer#320]
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.reflect.Constructor java.lang.Class.getConstructor(java.lang.Class[])' on a null object reference
        at cn.jzvd.Jzvd.startVideo(Jzvd.java:773)
        at cn.jzvd.JzvdStd.startVideo(JzvdStd.java:264)
        at cn.jzvd.Jzvd.startVideoAfterPreloading(Jzvd.java:593)

**Comment by lipangit** [comment]
你做了哪些修改，这个class是setup传进来的

**Comment by uzaysan** [comment]
> What changes have you made, this class is passed in through setup

This happens when user play music on background. User listen music. When jzvd starts to play music stops and video starts. But sometimes bug happens. jzvd.releaseAllVideos method doesnt work and video keep playing on background. And you cant play new videos. Only solution is closing app.
