### ISSUE TITLE
is:issue is:open 用了好多个版本，甚至使用该demo在安卓4.4下直接报错或不能播放视频，最低不是能支持到16的吗？我试了另一个播放器也是基于bilibili的却是可以播放

### ISSUE THREAD

**Issue by smapie** [Jzvd/JiaoZiVideoPlayer#321]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by smapie** [comment]
setContentView(R.layout.activity_main);
        JzvdStd jzvdStd = (JzvdStd) findViewById(R.id.jz_video);
        jzvdStd.setUp("https://vod.cdbaiyou.com/20210103/CxX4IOzg/index.m3u8", "饺子闭眼睛");
==========直接用安卓模拟器api19报load fail =================
E/MediaPlayer: Should have subtitle controller already set
I/JZVD: onVideoSizeChanged  [-1660745728] 
    onPrepared  [-1660745728] 
I/JZResizeTextureView: onMeasure  [-1657132680] 
    widthMeasureSpec  [MeasureSpec: EXACTLY 2055]
    heightMeasureSpec [MeasureSpec: EXACTLY 500]
I/JZResizeTextureView: onMeasure  [-1657132680] 
    widthMeasureSpec  [MeasureSpec: EXACTLY 2055]
    heightMeasureSpec [MeasureSpec: EXACTLY 500]
I/JZResizeTextureView: onMeasure  [-1657132680] 
    widthMeasureSpec  [MeasureSpec: EXACTLY 2055]
    heightMeasureSpec [MeasureSpec: EXACTLY 500]
I/JZResizeTextureView: onMeasure  [-1657132680] 
I/JZResizeTextureView: widthMeasureSpec  [MeasureSpec: EXACTLY 2055]
E/MediaPlayer: error (1, -2147483648)
E/MediaPlayer: Error (1,-2147483648)
I/JZResizeTextureView: heightMeasureSpec [MeasureSpec: EXACTLY 500]
E/JZVD: onError 1 - -2147483648 [-1660745728] 
I/JZVD: onStateError  [-1660745728]

**Comment by lipangit** [comment]
切换ijk内核，能不能波取决于内核

**Comment by Liberations** [comment]
检查自带videoview是否支持，尝试切换播放内核

**Comment by lipangit** [comment]
没错  是这个思路
