### ISSUE TITLE
是否可以一直显示进度条？

### ISSUE THREAD

**Issue by yangy9593** [Jzvd/JiaoZiVideoPlayer#325]
**需求描述
是否可以常显示此进度条？有尝试重写，但总有一些问题，来请教一下。
![image](https://user-images.githubusercontent.com/11763442/108688407-d2c6f180-7532-11eb-916f-91a9ffe29661.png)

**其他app是否实现

**截图或者小视频说明

**Comment by Liberations** [comment]
不知道为啥有这需求。。。 
集成JzvdStd 重写
`@Override
    public void startDismissControlViewTimer() {
        //super.startDismissControlViewTimer();
    }

    @Override
    public void setAllControlsVisiblity(int topCon, int bottomCon, int startBtn, int loadingPro, int posterImg, int bottomPro, int retryLayout) {
        super.setAllControlsVisiblity(topCon, View.VISIBLE, startBtn, loadingPro, posterImg, bottomPro, retryLayout);
    }`

**Comment by yangy9593** [comment]
这样重写会导致一些问题，比如：要点击好几下才能暂停。感觉要重写的部分有点多，我再研究研究吧，感谢回复。
