### ISSUE TITLE
有些视频在三星S8上播放失败（JZ7.6.0，手机 三星 Galaxy S8）

### ISSUE THREAD

**Issue by stevenMieMie** [Jzvd/JiaoZiVideoPlayer#329]
同样的播放地址在其它手机，或者其它播放地址都是能够正常播放的，日志这边没有分析出什么来

日志如下：
03-08 13:00:00.018 D/MSF.C.NetConnTag( 4807): pa ok: 6041
03-08 13:00:00.019 D/DualConnContext( 4807): tryDualConn
03-08 13:00:00.021 D/MSF.C.NetConnTag( 4807): netSend ssoSeq:6041 uin:*4058 cmd:GTcxIAkuJnQZKj0kNj0CPz4 6124 54ba6bc
03-08 13:00:00.030 V/APM_AudioPolicyManager(  696): AudioPolicyManager:setRecordSilenced(uid:10170, silenced:0)
03-08 13:00:00.034 I/LiveIconManager(24675): onReceive: com.samsung.action.EVERY_MINUTE_CLOCK_UPDATE
03-08 13:00:00.039 D/KeyguardUpdateMonitor( 2215): handleTimeUpdate
03-08 13:00:00.040 D/KeyguardServiceBoxContainer( 2215): refreshTime() 1
03-08 13:00:00.053 D/QSClockBellTower( 2215): He is ready to ring the bell. (((timeText:13:00, skipUpdateForDemo:false, dateText:3月8日, 周一)))
03-08 13:00:00.054 D/QSClock ( 2215): status_bar_clock notifyTimeChanged(currentTime:13:00) mClockVisibleByPolicy:true, mClockVisibleByUser:true, visible?true, parent:android.widget.LinearLayout{962d870 V.E...... ......ID 0,0-167,96 #7f0a02de app:id/left_clock_container}
03-08 13:00:00.054 D/QSClockBellTower( 2215): Everyone heard the bell. run(currentTime:1615179600053,   getTime():Mon Mar 08 13:00:00 GMT+08:00 2021,   getTimeZone():libcore.util.ZoneInfo[id="Asia/Shanghai",mRawOffset=28800000,mEarliestRawOffset=28800000,mUseDst=false,mDstSavings=0,transitions=28])
03-08 13:00:00.059 D/MSF.C.NetConnTag( 4807): netRecv ssoSeq:6041 uin:*4058 cmd:GTcxIAkuJnQZKj0kNj0CPz4 6152 cross:0
03-08 13:00:00.077 I/StackScroller( 2215): ADJUST STACK.TRANSLATION
03-08 13:00:00.083 I/chatty  ( 2215): uid=10043(com.samsung.android.app.aodservice) com.android.systemui identical 1 line
03-08 13:00:00.083 I/StackScroller( 2215): ADJUST STACK.TRANSLATION
03-08 13:00:00.101 I/qti_sensors_hal(  664): processReportInd: Light - 0 0
03-08 13:00:00.483 D/InputReader( 1591): Input event(5): value=1 when=39575.895000
03-08 13:00:00.484 I/InputReader( 1591): Touch event's action is 0x0 (deviceType=0) [pCnt=1, s=0.2 ] when=39575.895000
03-08 13:00:00.485 I/InputDispatcher( 1591): Delivering touch to (2215): action: 0x4, displayId: 0, '87b8312', toolType: 1
03-08 13:00:00.485 I/InputDispatcher( 1591): Delivering touch to (2215): action: 0x4, displayId: 0, '30511b0', toolType: 1
03-08 13:00:00.490 I/InputDispatcher( 1591): Delivering touch to (25717): action: 0x0, displayId: 0, '6885dec', toolType: 1
03-08 13:00:00.495 D/ViewRootImpl@8d26e2f[MainActivity](25717): ViewPostIme pointer 0
03-08 13:00:00.512 D/InputReader( 1591): Input event(5): value=0 when=39575.923891
03-08 13:00:00.512 I/InputReader( 1591): Touch event's action is 0x1 (deviceType=0) [pCnt=1, s=] when=39575.923891
03-08 13:00:00.513 I/InputDispatcher( 1591): Delivering touch to (25717): action: 0x1, displayId: 0, '6885dec', toolType: 1
03-08 13:00:00.513 D/ViewRootImpl@8d26e2f[MainActivity](25717): ViewPostIme pointer 1
03-08 13:00:00.517 I/JZVD    (25717): onClick start [77623056]
03-08 13:00:00.520 D/JZVD    (25717): startVideo [77623056]
03-08 13:00:00.520 D/JZVD    (25717): addTextureView [77623056]
03-08 13:00:00.521 W/AudioManager(25717): Use of stream types is deprecated for operations other than volume control
03-08 13:00:00.521 W/AudioManager(25717): See the documentation of requestAudioFocus() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-08 13:00:00.525 I/MediaFocusControl( 1591): requestAudioFocus() from uid/pid 10335/25717 clientId=android.media.AudioManager@ce4ccbecn.jzvd.Jzvd$1@cc1411f callingPack=com.dogesoft.joywok.modules req=2 flags=0x0 sdk=29
03-08 13:00:00.526 D/MediaFocusControl( 1591): selectFocusStack, uid = 10335, appDevice = 0, device = 2
03-08 13:00:00.527 D/AudioManager(25717): requestAudioFocus status : 1
03-08 13:00:00.527 I/JZVD    (25717): onStatePreparing  [77623056]
03-08 13:00:00.534 I/JZResizeTextureView(25717): onMeasure  [193385304]
03-08 13:00:00.534 I/JZResizeTextureView(25717): onMeasure  [193385304]
03-08 13:00:00.554 D/ViewRootImpl@8d26e2f[MainActivity](25717): Relayout returned: old=[0,0][1440,2960] new=[0,0][1440,2960] result=0x1 surface={valid=true 516462862336} changed=false
03-08 13:00:00.561 I/MediaPlayer(25717): Need to enable context aware info
03-08 13:00:00.561 V/MediaPlayer-JNI(25717): native_setup
03-08 13:00:00.561 V/MediaPlayerNative(25717): constructor
03-08 13:00:00.570 V/MediaPlayerNative(25717): setListener
03-08 13:00:00.578 W/MediaPlayer(25717): Use of stream types is deprecated for operations other than volume control
03-08 13:00:00.578 W/MediaPlayer(25717): See the documentation of setAudioStreamType() for what to use instead with android.media.AudioAttributes to qualify your playback use case
03-08 13:00:00.581 V/MediaPlayer-JNI(25717): setVolume: left 1.000000  right 1.000000
03-08 13:00:00.581 V/MediaPlayerNative(25717): MediaPlayer::setVolume(1.000000, 1.000000)
03-08 13:00:00.581 V/MediaPlayer-JNI(25717): setAuxEffectSendLevel: level 0.000000
03-08 13:00:00.581 V/MediaPlayerNative(25717): MediaPlayer::setAuxEffectSendLevel(0.000000)
03-08 13:00:00.581 V/MediaPlayer-JNI(25717): setAudioStreamType: 3
03-08 13:00:00.581 V/MediaPlayerNative(25717): MediaPlayer::setAudioStreamType
03-08 13:00:00.581 V/MediaPlayer-JNI(25717): setLooping: 0
03-08 13:00:00.581 V/MediaPlayerNative(25717): MediaPlayer::setLooping
03-08 13:00:00.581 W/MediaPlayer(25717): setScreenOnWhilePlaying(true) is ineffective without a SurfaceHolder
03-08 13:00:00.582 V/MediaHTTPService(25717): MediaHTTPService(android.media.MediaHTTPService@adcfcb1): Cookies: null
03-08 13:00:00.584 V/MediaPlayerService( 1014): Create new client(9) from pid 25717, uid 10335,
03-08 13:00:00.585 V/MediaPlayerService( 1014): player type = 4
03-08 13:00:00.586 D/NuPlayerDriver( 1014): NuPlayerDriver(0xeba66300) created, clientPid(25717)
03-08 13:00:00.588 V/AudioSink( 1014): AudioOutput(81)
03-08 13:00:00.588 V/NuPlayer( 1014): kWhatSetAudioSink
03-08 13:00:00.588 V/NuPlayerDriver( 1014): setDataSource(0xeba66300) url(https://<suppressed>)
03-08 13:00:00.588 V/NuPlayer( 1014): setDataSourceAsync GenericSource with url
03-08 13:00:00.588 D/NuPlayer( 1014): setDataSource: set mIsHTTP = TRUE
03-08 13:00:00.588 V/NuPlayer( 1014): kWhatSetDataSource
03-08 13:00:00.589 V/MediaPlayerNative(25717): setVideoSurfaceTexture
03-08 13:00:00.589 V/MediaPlayerService( 1014): [9] setVideoSurfaceTexture(0x0)
03-08 13:00:00.589 V/MediaPlayerNative(25717): prepareAsync
03-08 13:00:00.589 V/MediaPlayerService( 1014): [9] setAudioStreamType(3)
03-08 13:00:00.589 V/MediaPlayerService( 1014): [9] prepareAsync
03-08 13:00:00.589 V/NuPlayerDriver( 1014): prepareAsync(0xeba66300)
03-08 13:00:00.589 V/NuPlayer( 1014): prepareAsync
03-08 13:00:00.589 V/NuPlayer( 1014): onMessageReceived kWhatPrepare
03-08 13:00:00.590 I/MediaMonitor( 1014): MediaMonitor()
03-08 13:00:00.590 W/MediaPlayer(25717): setScreenOnWhilePlaying(true) is ineffective for Surface
03-08 13:00:00.590 V/MediaPlayer-JNI(25717): setVideoSurface
03-08 13:00:00.590 V/MediaPlayerNative(25717): setVideoSurfaceTexture
03-08 13:00:00.590 V/MediaHTTPService(25717): makeHTTPConnection: CookieManager created: java.net.CookieManager@2843517
03-08 13:00:00.590 V/MediaPlayerService( 1014): [9] setVideoSurfaceTexture(0xeba92240)
03-08 13:00:00.590 V/MediaHTTPService(25717): makeHTTPConnection(android.media.MediaHTTPService@adcfcb1): cookieHandler: java.net.CookieManager@2843517 Cookies: null
03-08 13:00:00.590 D/SurfaceUtils( 1014): connecting to surface 0xebafd808, reason setVideoSurfaceTexture
03-08 13:00:00.591 V/NuPlayerDriver( 1014): setVideoSurfaceTexture(0xeba66300)
03-08 13:00:00.591 D/NuPlayer( 1014): onSetVideoSurface(0xeba2a000, no video decoder)
03-08 13:00:00.599 V/NuPlayer( 1014): performSetSurface
03-08 13:00:00.599 V/NuPlayerDriver( 1014): notifySetSurfaceComplete(0xeba66300)
03-08 13:00:00.599 I/DataSource( 1014): [player] setReadTimeOut with 15000ms
03-08 13:00:00.599 D/MediaHTTPConnection(25717): setReadTimeOut =  15000ms
03-08 13:00:00.600 I/RemoteDisplayService( 1046): There is no RemoteDisplay
03-08 13:00:00.602 D/NetworkSecurityConfig(25717): No Network Security Config specified, using platform default
03-08 13:00:00.602 D/MediaHTTPConnection(25717): setReadTimeout with 15000ms
03-08 13:00:00.603 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:00.603 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:00.604 D/EnterpriseController( 1017): netId is 0
03-08 13:00:00.605 E/Netd    ( 1017): getNetworkForDns: getNetId from enterpriseCtrl is netid 0
03-08 13:00:00.605 D/DnsProxyListener( 1017): DNSDBG::dns addrinfo af 2
03-08 13:00:00.821 D/TcpOptimizer(25717): TcpOptimizer-ON
03-08 13:00:00.854 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:00.856 D/SecStatusBarWifiView( 2215): updateState: WifiIconState(resId=2131232630, visible=true, activityId=2131232636)
03-08 13:00:00.945 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = com.sec.android.sdhms, uid = 1000
03-08 13:00:00.991 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:01.020 I/System.out(25717): (HTTPLog)-Thread-1760-177451757: getTransferStream : ContentLength=123096581, method=GET, HTTPVersion=http/1.1
03-08 13:00:01.029 D/MDC     ( 1591): onReceive com.samsung.intent.action.BIG_DATA_MOBILE_DATA
03-08 13:00:01.029 D/MDC     ( 1591): onReceive com.samsung.intent.action.BIG_DATA_MOBILE_DATA category = DOWN
03-08 13:00:01.032 D/MDC     ( 1591): [DSTA] mDownloadList.size() : 10
03-08 13:00:01.049 I/MediaHTTPConnection(25717): response code = 200
03-08 13:00:01.050 I/DataSource( 1014): [player] Set Mimetype[video/mp4]
03-08 13:00:01.050 I/DataSource( 1014): Set isPlayer is [NuPlayer]
03-08 13:00:01.050 I/NuCachedSource2( 1014): [player] NuCachedSource2
03-08 13:00:01.091 D/MSF.D.QLog( 8566): QLog init
03-08 13:00:01.170 D/HTTPBase( 1014): [1] Network BandWidth = 0 Kbps
03-08 13:00:01.218 D/init_log( 8566): useNewLog false MSF=false QLogBean=false isGrayVersion|DebugVersion=falsefalse EncryptedKeyfalse
03-08 13:00:01.307 D/MSF.D.QLog( 4807): QLog init
03-08 13:00:01.419 D/init_log( 4807): useNewLog false MSF=false QLogBean=false isGrayVersion|DebugVersion=falsefalse EncryptedKeyfalse
03-08 13:00:01.453 I/NuCachedSource2( 1014): [player] new range: offset= 122599954
03-08 13:00:01.556 D/MediaHTTPConnection(25717): setReadTimeout with 15000ms
03-08 13:00:01.557 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:01.557 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:01.727 I/MediaHTTPConnection(25717): response code = 206
03-08 13:00:01.857 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:01.992 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:02.187 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
03-08 13:00:02.204 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
03-08 13:00:02.233 I/WifiStateMachine( 1591): checkScoreBasedQuality -  mPreviousScore[0]:96 mPreviousScore[1]:96 mPreviousScore[2]:96 s2Score:96mPrevoiusScoreAverage:96
03-08 13:00:02.413 I/NuCachedSource2( 1014): [player] new range: offset= 0
03-08 13:00:02.436 D/MediaHTTPConnection(25717): setReadTimeout with 15000ms
03-08 13:00:02.438 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:02.438 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:02.475 I/System.out(25717): (HTTPLog)-Thread-1760-18232290: getTransferStream : ContentLength=123096581, method=GET, HTTPVersion=http/1.1
03-08 13:00:02.481 I/MediaHTTPConnection(25717): response code = 200
03-08 13:00:02.481 D/MDC     ( 1591): onReceive com.samsung.intent.action.BIG_DATA_MOBILE_DATA
03-08 13:00:02.481 D/MDC     ( 1591): onReceive com.samsung.intent.action.BIG_DATA_MOBILE_DATA category = DOWN
03-08 13:00:02.481 D/MDC     ( 1591): [DSTA] mDownloadList.size() : 11
03-08 13:00:02.483 W/System  (25717): A resource failed to call release.
03-08 13:00:02.656 I/NuCachedSource2( 1014): [player] new range: offset= 122599954
03-08 13:00:02.759 D/MediaHTTPConnection(25717): setReadTimeout with 15000ms
03-08 13:00:02.760 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:02.760 I/System.out(25717): (HTTPLog)-Static: isSBSettingEnabled false
03-08 13:00:02.850 D/NetSpeedPolicy( 1591): bg app size is 0.
03-08 13:00:02.850 D/NetSpeedPolicy( 1591): realese All Apps Limit, mLimitAppList size = 0
03-08 13:00:02.861 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:02.974 I/MediaHTTPConnection(25717): response code = 206
03-08 13:00:02.992 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:03.106 I/SurfaceFlinger(  698): SFWD update time=39578517668599
03-08 13:00:03.473 E/GenericSource( 1014): initFromDataSource, source has no track!
03-08 13:00:03.474 E/GenericSource( 1014): Failed to init from data source!
03-08 13:00:03.474 V/NuPlayer( 1014): Source::notifyPrepared -2147483648
03-08 13:00:03.474 V/NuPlayer( 1014): NuPlayer::onSourceNotify Source::kWhatPrepared source: 0xebadea00
03-08 13:00:03.474 V/NuPlayer( 1014): performDecoderFlush audio=2, video=2
03-08 13:00:03.474 V/NuPlayerDriver( 1014): notifyPrepareCompleted -2147483648
03-08 13:00:03.474 D/NuPlayerDriver( 1014): notifyListener_l(0xeba66300), (100, 1, -2147483648, -1), loop setting(0, 0)
03-08 13:00:03.474 V/MediaPlayerService( 1014): [9] notify (100, 1, -2147483648)
03-08 13:00:03.474 V/MediaPlayerNative(25717): message received msg=300, ext1=0, ext2=0
03-08 13:00:03.474 V/MediaPlayerNative(25717): Received SEC_MM_PLAYER_CONTEXT_AWARE
03-08 13:00:03.474 V/MediaPlayerNative(25717): callback application
03-08 13:00:03.474 V/MediaPlayerNative(25717): back from callback
03-08 13:00:03.475 V/MediaPlayerNative(25717): message received msg=100, ext1=1, ext2=-2147483648
03-08 13:00:03.475 E/MediaPlayerNative(25717): error (1, -2147483648)
03-08 13:00:03.475 V/MediaPlayerNative(25717): callback application
03-08 13:00:03.476 V/MediaPlayerNative(25717): back from callback
03-08 13:00:03.476 E/MediaPlayer(25717): Error (1,-2147483648)
03-08 13:00:03.478 E/JZVD    (25717): onError 1 - -2147483648 [77623056]
03-08 13:00:03.478 I/JZVD    (25717): onStateError  [77623056]
03-08 13:00:03.482 V/MediaPlayer-JNI(25717): setVideoSurface
03-08 13:00:03.482 V/MediaPlayerNative(25717): setVideoSurfaceTexture
03-08 13:00:03.483 V/MediaPlayerService( 1014): [9] setVideoSurfaceTexture(0x0)
03-08 13:00:03.483 V/NuPlayerDriver( 1014): setVideoSurfaceTexture(0xeba66300)
03-08 13:00:03.485 D/NuPlayer( 1014): onSetVideoSurface(0x0, no video decoder)
03-08 13:00:03.486 V/NuPlayer( 1014): performSetSurface
03-08 13:00:03.486 V/NuPlayerDriver( 1014): notifySetSurfaceComplete(0xeba66300)
03-08 13:00:03.486 D/SurfaceUtils( 1014): disconnecting from surface 0xebafd808, reason disconnectNativeWindow
03-08 13:00:03.490 V/MediaPlayer(25717): resetDrmState:  mDrmInfo=null mDrmProvisioningThread=null mPrepareDrmInProgress=false mActiveDrmScheme=false
03-08 13:00:03.490 V/MediaPlayer(25717): cleanDrmObj: mDrmObj=null mDrmSessionId=null
03-08 13:00:03.490 V/MediaPlayer-JNI(25717): release
03-08 13:00:03.490 V/MediaPlayerNative(25717): setListener
03-08 13:00:03.490 V/MediaPlayerNative(25717): disconnect
03-08 13:00:03.491 V/MediaPlayerService( 1014): disconnect(9) from pid 25717
03-08 13:00:03.491 D/NuPlayerDriver( 1014): reset(0xeba66300) at state 2
03-08 13:00:03.491 V/NuPlayerDriver( 1014): updateMetrics(0xeba66300) from reset at state 2
03-08 13:00:03.491 V/NuPlayer( 1014): NuPlayer::getStats()
03-08 13:00:03.492 V/NuPlayer( 1014): kWhatGetStats
03-08 13:00:03.492 V/NuPlayer( 1014): updateInternalTimers()
03-08 13:00:03.492 V/NuPlayer( 1014): updatePlaybackTimer(snap)  time                    0 (updateInternalTimers)
03-08 13:00:03.492 V/NuPlayer( 1014): updateRebufferingTimer(snap)  time                    0 (exiting 0)
03-08 13:00:03.492 V/NuPlayerDriver( 1014): logMetrics(0xeba66300) from reset at state 2
03-08 13:00:03.495 D/NuPlayerDriver( 1014): notifyListener_l(0xeba66300), (8, 0, 0, -1), loop setting(0, 0)
03-08 13:00:03.496 V/NuPlayer( 1014): kWhatReset
03-08 13:00:03.496 V/NuPlayer( 1014): setDecoderBooster enable = No
03-08 13:00:03.496 V/NuPlayer( 1014): updatePlaybackTimer(stop)  time                    0 (kWhatReset)
03-08 13:00:03.496 V/NuPlayer( 1014): updateRebufferingTimer(stop)  time                    0 (exiting 1)
03-08 13:00:03.496 V/NuPlayer( 1014): performDecoderFlush audio=2, video=2
03-08 13:00:03.496 V/NuPlayer( 1014): performReset
03-08 13:00:03.496 V/NuPlayer( 1014): updatePlaybackTimer(stop)  time                    0 (performReset)
03-08 13:00:03.496 V/NuPlayer( 1014): updateRebufferingTimer(stop)  time                    0 (exiting 1)
03-08 13:00:03.496 D/NuPlayerDriver( 1014): notifyResetComplete(0xeba66300)
03-08 13:00:03.499 V/NuPlayerDriver( 1014): ~NuPlayerDriver(0xeba66300)
03-08 13:00:03.500 V/NuPlayerDriver( 1014): updateMetrics(0xeba66300) from destructor at state 0
03-08 13:00:03.500 V/NuPlayer( 1014): NuPlayer::getStats()
03-08 13:00:03.500 V/NuPlayer( 1014): updateInternalTimers()
03-08 13:00:03.500 V/NuPlayer( 1014): updatePlaybackTimer(snap)  time                    0 (updateInternalTimers)
03-08 13:00:03.500 V/NuPlayer( 1014): updateRebufferingTimer(snap)  time                    0 (exiting 0)
03-08 13:00:03.500 V/NuPlayerDriver( 1014): logMetrics(0xeba66300) from destructor at state 0
03-08 13:00:03.500 V/NuPlayerDriver( 1014): nothing to record (only 3 fields)
03-08 13:00:03.501 V/MediaPlayerNative(25717): destructor
03-08 13:00:03.502 V/MediaPlayerService( 1014): Client(9) destructor pid = 25717
03-08 13:00:03.502 V/AudioSink( 1014): +++ close
03-08 13:00:03.502 V/AudioSink( 1014): --- close
03-08 13:00:03.503 V/MediaPlayerService( 1014): disconnect(9) from pid 25717
03-08 13:00:03.504 V/MediaPlayerNative(25717): disconnect
03-08 13:00:03.544 I/NuCachedSource2( 1014): [player] ~NuCachedSource2
03-08 13:00:03.885 D/WifiTrafficPoller( 1591): TrafficStats TxPkts=16609 RxPkts=56059 TxBytes=1269244 RxBytes=31198169 , Foreground uid=10335 pkgName=com.dogesoft.joywok.modules TxPackets=1149 RxPackets=1234 TxBytes=62235 RxBytes=1795607
03-08 13:00:03.887 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:03.994 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:04.895 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:04.899 D/SecStatusBarWifiView( 2215): updateState: WifiIconState(resId=2131232630, visible=true, activityId=2131232635)
03-08 13:00:04.995 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:05.236 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
03-08 13:00:05.281 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
03-08 13:00:05.390 I/WifiStateMachine( 1591): checkScoreBasedQuality -  mPreviousScore[0]:96 mPreviousScore[1]:96 mPreviousScore[2]:96 s2Score:95mPrevoiusScoreAverage:96
03-08 13:00:05.908 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:05.913 D/SecStatusBarWifiView( 2215): updateState: WifiIconState(resId=2131232630, visible=true, activityId=2131232655)
03-08 13:00:05.995 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:06.938 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:07.000 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:07.943 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:07.946 V/APM_AudioPolicyManager(  696): getAudioPolicyConfig: audioParam;outDevice
03-08 13:00:07.947 V/APM_AudioPolicyManager(  696): getNewOutputDevice() selected device 0
03-08 13:00:07.947 V/APM_AudioPolicyManager(  696): ### curdevice : 2
03-08 13:00:08.001 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:08.393 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) before calling iface.getLinkLayerStats
03-08 13:00:08.445 I/WifiVendorHal( 1591): getWifiLinkLayerStats(l.2973) after calling iface.getLinkLayerStats
03-08 13:00:08.494 I/WifiStateMachine( 1591): checkScoreBasedQuality -  mPreviousScore[0]:96 mPreviousScore[1]:96 mPreviousScore[2]:95 s2Score:96mPrevoiusScoreAverage:95
03-08 13:00:08.825 V/APM_AudioPolicyManager(  696): AudioPolicyManager:setRecordSilenced(uid:99000, silenced:1)
03-08 13:00:08.947 D/WifiPermissionsUtil( 1591): canAccessScanResults: pkgName = android, uid = 1000
03-08 13:00:09.003 I/tickcount:Thread-ASRResultThread(23481):  : VSP::In ASRResultThread :currrenID:-1isRunning:true
03-08 13:00:09.970 D/WifiTrafficPoller( 1591): TrafficStats TxPkts=16609 RxPkts=56064 TxBytes=1269244 RxBytes=31198988 , Foreground uid=10335 pkgName=com.dogesoft.joywok.modules TxPackets=1149 RxPackets=1234 TxBytes=62235 RxBytes=1795607

**Comment by Liberations** [comment]
看不出啥问题。尝试切换播放内核试试
