### ISSUE TITLE
在播放直播源m3u8的时候，播放失败了

### ISSUE THREAD

**Issue by MoonSawyer** [Jzvd/JiaoZiVideoPlayer#331]
在播放m3u8的时候，我发现，如果不在onDestroy中加一句Jzvd.releaseAllVideos();打开刚关闭的视频，显示，播放失败。感觉像是异常关闭的问题，是否可以加个cancel命令？
还有，我没有找到视频大小的暴露接口。在弄直播源的时候，我想加个播放进度追赶机制。是否可以加个视频参数的暴露接口？

**Comment by lipangit** [comment]
1Cancel命令做什么什么逻辑

2继承jzvdstd复写onprogress函数  取得视频大小

**Comment by MoonSawyer** [comment]
关于第一点。我使用播放器播放直播。在关闭后重新打开，会出现播放失败的问题。当时我没仔细研究代码。认为，可能是退出时，播放器组件没有正常关闭导致的。后来我自己发现，播放器好像会记录播放进度，感觉应该是重新打开跳进度导致播放失败。

**Comment by lipangit** [comment]
jzvd.save_progress=false不记路播放进度
