### ISSUE TITLE
设置伸缩模式

### ISSUE THREAD

**Issue by liulanghaitun** [Jzvd/JiaoZiVideoPlayer#338]
**需求描述
有时候播放视频的时候由于视频是拉伸模式，导致有时候字幕无法正常显示。

**其他app是否实现
是
**截图或者小视频说明
阿里云播放器内核支持拉伸模式:
setScaleMode: SCALE_ASPECT_FIT,SCALE_ASPECT_FILL,SCALE_TO_FILL

**Comment by TrueloveSomeGIRl** [comment]
如果字是视频里面的拉升了是看不到的 除非是外挂字幕
