### ISSUE TITLE
如何使用JZMediaExo 这个模式？

### ISSUE THREAD

**Issue by nikolamakin** [Jzvd/JiaoZiVideoPlayer#339]
我进行了如下操作：
implementation 'com.google.android.exoplayer:exoplayer:2.13.2'
implementation 'cn.jzvd:jiaozivideoplayer:7.6.0'

然后在activity中
jzvdStd.setMediaInterface(JZMediaExo::class.java);
JZMediaExo不存在

如何引入JZMediaExo

感谢作者回复

**Comment by Liberations** [comment]
参考demo JZMediaExo 复制到你的工程
