### ISSUE TITLE
设置缩略图 明显不对啊jzvdStd.posterImageView.setImage 

### ISSUE THREAD

**Issue by peng093** [Jzvd/JiaoZiVideoPlayer#346]
**什么jzvd版本
implementation 'cn.jzvd:jiaozivideoplayer:7.6.0'

posterImageView属于ImageView，原生的ImageView没有setImage 这个方法啊 这么明显的错误。。。

**Comment by lipangit** [comment]
看demo 根据自己的项目用哪款imageloader设置缩略图



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月27日(周二) 上午9:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 设置缩略图 明显不对啊jzvdStd.posterImageView.setImage  (#346)




 
**什么jzvd版本
 implementation 'cn.jzvd:jiaozivideoplayer:7.6.0'
 
posterImageView属于ImageView，原生的ImageView没有setImage 这个方法啊 这么明显的错误。。。
