### ISSUE TITLE
拖动进度条到快播放完的时候，点击重播，进度条就错乱了。

### ISSUE THREAD

**Issue by jqorz** [Jzvd/JiaoZiVideoPlayer#348]
7.6.0版本，用demo测试，连重播按钮都不显示，直接就从头播放，时间显示和进度条完全不匹配。
![Uploading device-2021-05-06-114958.png…]()
PS：对作者的水平很怀疑，我用过三个版本，每个版本都有bug。

**Comment by Liberations** [comment]
bug肯定是有，重播按钮显不显示跟onCompletion是否被播放器内核调用有关。如果 jzDataSource.looping = true 开启循环播放那么就没有重播按钮。时间进度条不匹配可能是这个提交导致的 参考 #340
