### ISSUE TITLE
7.4.1 版本 一个空指针

### ISSUE THREAD

**Issue by yilylong** [Jzvd/JiaoZiVideoPlayer#350]
**什么jzvd版本
7.4.1 不知道新版是否已经修复了

**截图或者视频说明情况
![](https://raw.githubusercontent.com/yilylong/ImageResource/master/jzvd_error1.png)
![](https://raw.githubusercontent.com/yilylong/ImageResource/master/jzvd_error2.png)

**Comment by TrueloveSomeGIRl** [comment]
提供相关代码 这里的代码定位不到你是怎么实际操作的 导致空指针

**Comment by yilylong** [comment]
> 提供相关代码 这里的代码定位不到你是怎么实际操作的 导致空指针

我记得给了图片的怎么看不到图片了  错误是用户使用中上传的 具体操作方式不清楚
<img src='https://raw.githubusercontent.com/yilylong/ImageResource/master/jzvd_error1.png'>
<img src='https://raw.githubusercontent.com/yilylong/ImageResource/master/jzvd_error2.png'>

**Comment by yilylong** [comment]
public void gotoNormalScreen() {//goback本质上是goto
        gobakFullscreenTime = System.currentTimeMillis();//退出全屏
        ViewGroup vg = (ViewGroup) (JZUtils.scanForActivity(jzvdContext)).getWindow().getDecorView();
        vg.removeView(this);
//        CONTAINER_LIST.getLast().removeAllViews();
        CONTAINER_LIST.getLast().removeViewAt(blockIndex);//remove block
        CONTAINER_LIST.getLast().addView(this, blockIndex, blockLayoutParams);
        CONTAINER_LIST.pop();
        setScreenNormal();//这块可以放到jzvd中
        JZUtils.showStatusBar(jzvdContext);
        JZUtils.setRequestedOrientation(jzvdContext, NORMAL_ORIENTATION);
        JZUtils.showSystemUI(jzvdContext);
    }
CONTAINER_LIST.getLast().addView(this, blockIndex, blockLayoutParams);这句报错  CONTAINER_LIST.getLast()为null

**Comment by Liberations** [comment]
检查是否在onPause中release导致的。
