### ISSUE TITLE
7.6.0的版本，点击播放视频进度条正常进行，几秒钟之后视频进度条下移，不要手动进行，在视频下方的进度条停止不动，显示异常

### ISSUE THREAD

**Issue by zhaoyangxihui** [Jzvd/JiaoZiVideoPlayer#352]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by Liberations** [comment]
#348
