### ISSUE TITLE
layout\jz_layout_std.xml这个布局文件能不能根布局加个id，便于设置背景颜色

### ISSUE THREAD

**Issue by 284361303** [Jzvd/JiaoZiVideoPlayer#359]
**需求描述
layout\jz_layout_std.xml目前这个布局文件的根布局没有id，并且源码给设置死了黑色，有的视频过小没有充满全屏就有黑边，我们的项目主题是白色的，不得已把源码中的library给down下来了。有了id我就可以设置背景颜色了，就不用down源码了，减小app体积

**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
继承javdstd 复写getlayoutbyid函数，设置自己的xml布局，自行设置布局的id。最后复写init函数findviewbyid找到自己刚添加的id



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月3日(周四) 晚上9:39
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] layout\jz_layout_std.xml这个布局文件能不能根布局加个id，便于设置背景颜色 (#359)




 
**需求描述
 layout\jz_layout_std.xml目前这个布局文件的根布局没有id，并且源码给设置死了黑色，有的视频过小没有充满全屏就有黑边，我们的项目主题是白色的，不得已把源码中的library给down下来了。有了id我就可以设置背景颜色了，就不用down源码了，减小app体积
 
**其他app是否实现
 
**截图或者小视频说明
