### ISSUE TITLE
startPreloading() 在demo在运行无效，一直转圈圈等待

### ISSUE THREAD

**Issue by Air1270613071** [Jzvd/JiaoZiVideoPlayer#361]
startPreloading() 在demo在运行无效，一直转圈圈等待

**Comment by Liberations** [comment]
url设置错了

**Comment by Air1270613071** [comment]
@Liberations 按你说的改了PreloadingActivity.java里的地址。点击 开始预加载 还是转圈圈，但是点击 预加载完播放 是没有问题。

**Comment by chenkexu** [comment]
我用的最新版本，点击“开始预加载”，还是一直在转圈圈。
