### ISSUE TITLE
不支持TV按键操作，不支持播放控制

### ISSUE THREAD

**Issue by qq578023708** [Jzvd/JiaoZiVideoPlayer#362]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

在TV上，无法响应OK键播放或者暂停，想利用Activity的KeyDown事件进行手动控制播放和暂停，发现没有相应的控制方法

**Comment by Liberations** [comment]
可以通过startButton.performClick();

**Comment by lipangit** [comment]
这个功能没有现成的，继承jzvdstd自己做按键操作，通过继承可以做任何事情，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月10日(周四) 上午9:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [Jzvd/JZVideo] 不支持TV按键操作，不支持播放控制 (#362)




 
可以通过startButton.performClick();

**Comment by Liberations** [comment]
楼上说的对
