### ISSUE TITLE
能加载本地视频吗？

### ISSUE THREAD

**Issue by lb1207087645** [Jzvd/JiaoZiVideoPlayer#363]
能加载本地视频吗？如果我要加载一个raw文件夹下的本地视频要怎么做？

**Comment by lipangit** [comment]
参考demo，里有一个播放assert下的视频



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月11日(周五) 上午10:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 能加载本地视频吗？ (#363)




 
能加载本地视频吗？如果我要加载一个raw文件夹下的本地视频要怎么做？
