### ISSUE TITLE
7.7.0 AGVIDEO右侧滑动调整音量触发空指针

### ISSUE THREAD

**Issue by xihan123** [Jzvd/JiaoZiVideoPlayer#373]
**什么jzvd版本
7.7.0

**什么播放器内核
ijk

**相关log是什么
Attempt to invoke virtual method 'int android.media.AudioManager.getStreamMaxVolume(int)' on a null object reference
"moveChange"、"onTouch"这两个方法

**demo是否有这个问题
有，高度自定义的AGVIDEO

**自己做了哪些修改
没有修改

**如何操作复现
使用AGVIDEO右侧滑动调整音量直接触发

**什么安卓版本，什么机型
全

**截图或者视频说明情况
![bug2](https://user-images.githubusercontent.com/44894509/124375367-63c58a80-dcd4-11eb-831b-002f063c7d32.png)

**Comment by ToxicR** [comment]
已修改，请查看最新的dev分支代码，在onStatePlaying中对mAudioManager进行了初始化
