### ISSUE TITLE
全屏方向问题

### ISSUE THREAD

**Issue by 900326** [Jzvd/JiaoZiVideoPlayer#374]
**什么jzvd版本
v7.6.0
**什么播放器内核
默认内核
**相关log是什么

**demo是否有这个问题
有
**自己做了哪些修改
在锁定竖向方向的情况下,全屏状态下,左右手势都是调整亮度,没有调整声音的,下图地方加个方向判断即可
![360截图187201178299113](https://user-images.githubusercontent.com/11885751/124538714-ae6b1200-de4e-11eb-99d8-6be77122f66b.png)

**如何操作复现
播放横竖屏俩个不同的方向的视频,全屏播放可复现
**什么安卓版本，什么机型

**截图或者视频说明情况
全屏时,默认都是横向播放,如果视频时竖向的,则会显的很小,和正常窗口播放一样,全屏状态下,点击缩小按钮,又会直接返回正常播放这状态,
看过其他播放器,全屏下,点击右下角的"按钮",会作横竖屏的切换,不是直接退出全屏,当然这个也是根据具体情况,具体业务定的,希望jzvd后续也可以支持,提供更完善的功能
希望可以加个视频宽高或方向的判断,如果是竖屏视频,点击全屏按钮时直接就竖向播放,如果是横向视频,点击全屏默认横向播放,
比如这样的视频,
![微信图片_20210706113947](https://user-images.githubusercontent.com/11885751/124539037-4a951900-de4f-11eb-8099-a8acd6bc34d1.jpg)

**Comment by Liberations** [comment]
你提交个PR

**Comment by 900326** [comment]
PR是什么,不懂

**Comment by Liberations** [comment]
把你的修改commit pull request上来
