### ISSUE TITLE
全屏播放完成不退出全屏点击重播后一直在加载

### ISSUE THREAD

**Issue by szhdev** [Jzvd/JiaoZiVideoPlayer#379]
**什么jzvd版本
'cn.jzvd:jiaozivideoplayer:7.7.0'

如题  下载的Demo也是如此

**Comment by Liberations** [comment]
`public class JzvdStdAutoCompleteAfterFullscreen extends JzvdStd {
    public JzvdStdAutoCompleteAfterFullscreen(Context context) {
        super(context);
    }

    public JzvdStdAutoCompleteAfterFullscreen(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void onCompletion() {
        if (screen == SCREEN_FULLSCREEN) {
            onStateAutoComplete();
        } else {
            super.onCompletion();
        }

    }
}`

**Comment by Liberations** [comment]
不知道之前为啥可以 现在不需要重写startVideo方法 你试试

**Comment by szhdev** [comment]
刚测试了一下 不重写startVideo方法 重播是可以的
