### ISSUE TITLE
如何显示视频的下载速度

### ISSUE THREAD

**Issue by hpp0hpp** [Jzvd/JiaoZiVideoPlayer#387]
**需求描述
如何在右上角显示视频的下载速度?
**其他app是否实现

**截图或者小视频说明

**Comment by TrueloveSomeGIRl** [comment]
市面上所有App显示的速度都是假的 ，这个只能自己添加布局 获取当前网速显示 做个假的样子

**Comment by hpp0hpp** [comment]
@TrueloveSomeGIRl 
我看到播放器内核logcat日志里面是有网速显示的.
