### ISSUE TITLE
 java.lang.NullPointerException

### ISSUE THREAD

**Issue by Sunshine-Joex** [Jzvd/JiaoZiVideoPlayer#39]
**7.1.0版本

**log日志：
 java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.os.Handler.post(java.lang.Runnable)' on a null object reference
at cn.jzvd.JZMediaSystem.pause(JZMediaSystem.java:67)

**我的代码里调用如下：
是在全屏的dialog里播放的，弹出弹窗的时候就crash
override fun onWindowFocusChanged(hasFocus: Boolean) {
        super.onWindowFocusChanged(hasFocus)
        video?.mediaInterface?.pause()
    }

**安卓版本：9.0，华为手机

**Comment by lipangit** [comment]
怎么引起的，哪个为空，兄弟研究一下
