### ISSUE TITLE
请问如何实现一个全局的播放器，在不同页面有不同的播放器样式，切换的时候还能够不间断播放

### ISSUE THREAD

**Issue by rockerkekex** [Jzvd/JiaoZiVideoPlayer#393]
现在需要实现一个需求，在一个页面播放一个音频或视频，跳转到其他页面之后，播放器样式会发生变化，同时要继续播放，请问有什么思路可以实现呢？
类似的app有 得到app,或者凤凰大健康的iOS版本，多谢！

**Comment by Liberations** [comment]
你可以参考列表到详情页的那个demo 至于ui长啥样可以完全自定义的。

**Comment by Liberations** [comment]
比如继承jzvdStd编写自己的布局 设置一个标志UI样式1 样式2...切换

**Comment by rockerkekex** [comment]
> 比如继承jzvdStd编写自己的布局 设置一个标志UI样式1 样式2...切换

非常感谢回复。按照这种思路，连续播放没有问题，但是切换布局文件碰到了点麻烦。

![截屏2021-09-13 上午10 30 16](https://user-images.githubusercontent.com/1932007/133015383-6da4e2d7-5ee1-4fd0-b727-2daacc67b8d5.png)
![截屏2021-09-13 上午10 30 29](https://user-images.githubusercontent.com/1932007/133015386-73cc7932-7ce1-4c38-b2d3-c56c18a6c2b0.png)

在CURRENT_JZVD ！= null的时候，该如何切换layout文件呢，如果remove再重新添加，播放也就会停止了吧。因为每个播放器界面差别很大，都放在一个文件里可能会非常麻烦，请问您说的切换样式，具体该如何实现呢？

**Comment by rockerkekex** [comment]
已经搞定了，最终还是在一个布局文件里，根据不同的类型去显示和隐藏一些视图

**Comment by Liberations** [comment]
好的
