### ISSUE TITLE
jzvd版本7.7.0 播放1080*2310的视频部分小分辨率手机播放失败

### ISSUE THREAD

**Issue by FlyLfy** [Jzvd/JiaoZiVideoPlayer#395]
**什么jzvd版本

**什么播放器内核

**相关log是什么

**demo是否有这个问题

**自己做了哪些修改

**如何操作复现

**什么安卓版本，什么机型

**截图或者视频说明情况

**Comment by Liberations** [comment]
试试自带的videoview是否播放正常。

**Comment by FlyLfy** [comment]
也是播放不了，该视频是从抖音上下载下来的

**Comment by Liberations** [comment]
> 也是播放不了，该视频是从抖音上下载下来的

尝试切换播放内核试试
