### ISSUE TITLE
How can I go forward or rewind for 5 seconds with double click?

### ISSUE THREAD

**Issue by mso45mso** [Jzvd/JiaoZiVideoPlayer#396]
**When I double click on the left and right of the screen, I want it to forward or rewind for 5 seconds.

**Comment by mso45mso** [comment]
And, how can I check if the video is playing now?

**Comment by Liberations** [comment]
onStatePlaying VIDEO is playing, JZMediaInterface.seekTo() to forward or rewind for 5 seconds.

**Comment by Liberations** [comment]
onStatePlaying VIDEO is playing, JZMediaInterface.seekTo() to forward or rewind for 5 seconds.
