### ISSUE TITLE
音频播放，如果播放器UI被划出屏幕，加载音频文件无法播放，滑回屏幕后才开始播放

### ISSUE THREAD

**Issue by rockerkekex** [Jzvd/JiaoZiVideoPlayer#402]
划出屏幕后，加载音频文件，日志里只展示  I/JZVD: onStatePreparing，滑动屏幕显示播放器后才会开始播放。
![611632714165_ pic](https://user-images.githubusercontent.com/1932007/134842560-30e9160d-bc4d-45ad-a555-c4aa3fd1717c.jpg)
![621632714190_ pic](https://user-images.githubusercontent.com/1932007/134842569-d2f079a8-d25e-43c0-b2a1-3d3e443ae30a.jpg)

**Comment by Liberations** [comment]
demo好像正常

**Comment by rockerkekex** [comment]
> demo好像正常

demo里没法模拟这种情况吧，demo里都是点击播放器界面开始播放，如果播放器界面划出了屏幕，加载音频文件后就没法播放了，滑动一下屏幕，播放器界面显示在屏幕里，才能正常开始播放。

**Comment by Liberations** [comment]
提供个demo我试试。
