### ISSUE TITLE
JiaoZiVideoPlayer怎样一开启activity就跳到上次播放进度,如果没有播放进度,再从零播放

### ISSUE THREAD

**Issue by a5258509** [Jzvd/JiaoZiVideoPlayer#404]
**需求描述

**其他app是否实现

**截图或者小视频说明

**Comment by Liberations** [comment]
`    public static void saveProgress(Context context, Object url, long progress) {
        if (!Jzvd.SAVE_PROGRESS) return;
        Log.i(TAG, "saveProgress: " + progress);
        if (progress < 5000) {
            progress = 0;
        }
        SharedPreferences spn = context.getSharedPreferences("JZVD_PROGRESS",
                Context.MODE_PRIVATE);
        SharedPreferences.Editor editor = spn.edit();
        editor.putLong("newVersion:" + url.toString(), progress).apply();
    }`
通过url去保存上次播放的位置 重新播放时读取保存值并seek

`  long position = JZUtils.getSavedProgress(getContext(), jzDataSource.getCurrentUrl());
                if (position != 0) {
                    mediaInterface.seekTo(position);//
                }`

**Comment by a5258509** [comment]
jiecaoplayer.setUp(jzDataSource, JzvdStd.SCREEN_NORMAL);
            Glide.with(this).load(img).into(jiecaoplayer.posterImageView);
            mediaInterface.seekTo(5000);
这个方法mediaInterface.seekTo(5000);在刚进到activity的时候就报错
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void cn.jzvd.JZMediaInterface.seekTo(long)' on a null object reference
是不是要单开个线程调用啊,还是怎么办?

**Comment by NingJinBo** [comment]
因为mediainterface只有在播放后才会赋值，所以直接调用seekTo会报错，使用seekToInAdvacne = time
jzvdStd.setUp(proxyUrl, title, Jzvd.SCREEN_NORMAL, JZMediaExo.class);
jzvdStd.seekToInAdvance = time;//上次播放时长
