### ISSUE TITLE
loadVideoScreenshot 获取当前帧，对应bitmap 错误。

### ISSUE THREAD

**Issue by Simon-Kjer** [Jzvd/JiaoZiVideoPlayer#431]
加载网络视频，在播放时暂停后，获取视频当前帧bitmap 但是获取的帧图是错误的，多个进度都是同一帧图片，和视频进度的帧对不上。希望帮忙指正。
 ~~~ java{
public static void loadVideoScreenshot(final Context context, String uri, ImageView imageView, long frameTimeMicros) {
        RequestOptions requestOptions = RequestOptions.frameOf(frameTimeMicros);
        requestOptions.set(FRAME_OPTION, MediaMetadataRetriever.OPTION_CLOSEST);
        requestOptions.transform(new BitmapTransformation() {
            @Override
            protected Bitmap transform(@NonNull BitmapPool pool, @NonNull Bitmap toTransform, int outWidth, int outHeight) {
                return toTransform;
            }
            @Override
            public void updateDiskCacheKey(MessageDigest messageDigest) {
                try {
                    messageDigest.update((context.getPackageName() + "RotateTransform").getBytes("utf-8"));
                 
                } catch (Exception e) {
                    e.printStackTrace();
                    
                }
            }
        });
        Glide.with(context).load(uri).apply(requestOptions).into(imageView);
    }
}

**Comment by Liberations** [comment]
frameTimeMicros重点观察这个参数是否跟视频节点跟上？

**Comment by NingJinBo** [comment]
这个问题是视频的时间戳没有乘以*1000，播放器的时间都是以毫秒为单位，视频应该是秒为单位，目前亲测比如播放到60s*1000是正常的显示当前60s这一帧的封面

**Comment by NingJinBo** [comment]
glide有延迟目前使用另外的2种方法都可以实现获取视频的某一帧
1.使用textureView的getBitmap方法
    public void updateFrontCover() {
        if (textureView != null) {
            Bitmap bitmap = textureView.getBitmap();
            if (bitmap != null) {
                posterImageView.setImageBitmap(bitmap);
            }
        }
    }
2.通过MediaMetadataRetriever获取视频某帧图片，网络图片的url
    /**
     * 获取视频指定微秒处的帧图片
     * url  网络url
     *timeUs 微秒 1秒=1000毫秒=1000000微秒，若时间不乘以1000则显示的第一帧的图片
     */
    public static Bitmap GetFramePictures(String url, long timeUs){
        Bitmap videoShortCut = null;
        String width = null;
        String height = null;
        MediaMetadataRetriever mediaMetadataRetriever = new MediaMetadataRetriever();
        try {
            if (url != null) {
                HashMap<String, String> headers;
                headers = new HashMap<>();
                headers.put("User-Agent", "Mozilla/5.0 (Linux; U; Android 4.4.2; zh-CN; MW-KW-001 Build/JRO03C) AppleWebKit/533.1 (KHTML, like Gecko) Version/4.0 UCBrowser/1.0.0.001 U4/0.8.0 Mobile Safari/533.1");
                mediaMetadataRetriever.setDataSource(url, headers);
            } else {
                //mmr.setDataSource(mFD, mOffset, mLength);
            }
            videoShortCut = mediaMetadataRetriever.getFrameAtTime(timeUs, MediaMetadataRetriever.OPTION_CLOSEST);
            width = mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_WIDTH);
            height = mediaMetadataRetriever.extractMetadata(MediaMetadataRetriever.METADATA_KEY_VIDEO_HEIGHT);
        } catch (IllegalArgumentException e) {
            Log.e("setFrameAtTimeWithView ERROR:" , e.toString(), e);
        }
        mediaMetadataRetriever.release();
        return  videoShortCut;
    }
