### ISSUE TITLE
请教下怎么截图

### ISSUE THREAD

**Issue by 1825492258** [Jzvd/JiaoZiVideoPlayer#442]
怎么获取当前播放的视图，然后我转成bitmap保存到本地。

**Comment by lipangit** [comment]
getcurrentbitmap（）。从surfaceview里取得当前图像



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月20日(周五) 中午11:47
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [Jzvd/JZVideo] 请教下怎么截图 (Issue #442)




 
怎么获取当前播放的视图，然后我转成bitmap保存到本地。

**Comment by 1825492258** [comment]
从这个jzVideo我怎么获取surfaceview

**Comment by 1825492258** [comment]
jzvdStd.mediaInterface.jzvd.textureView.getBitmap(); 这么吗？
