### ISSUE TITLE
play video from local storage but always preload

### ISSUE THREAD

**Issue by tusantrey2** [Jzvd/JiaoZiVideoPlayer#451]
i have a problem with a local video, when me implement to my code just show preload like this

![Screenshot_2022-06-27-23-01-01-35_051cc18165488e7fd55ab138ed602ae0](https://user-images.githubusercontent.com/55271736/175983276-92898dac-c3ef-42d9-aaee-3ff29306571b.jpg)

My code like this
`String title = "Video Player";`
`String path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/storage/emulated/0/Download/short.mp4";`
`mVideoView.setUp(path, title);`

and permission same like your **demo**

**Comment by tusantrey2** [comment]
> i have a problem with a local video, when me implement to my code just show preload like this
> 
> ![Screenshot_2022-06-27-23-01-01-35_051cc18165488e7fd55ab138ed602ae0](https://user-images.githubusercontent.com/55271736/175983276-92898dac-c3ef-42d9-aaee-3ff29306571b.jpg)
> 
> My code like this `String title = "Video Player";` `String path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/storage/emulated/0/Download/short.mp4";` `mVideoView.setUp(path, title);`
> 
> and permission same like your **demo**

Problem fixed after change code like this `String path = "/storage/emulated/0/Download/short.mp4";`

and this issue will be **closed**

**Comment by lipangit** [comment]
maybe the path is wrong . try the path in other player is it work?



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 28, 2022 01:11 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Jzvd/JZVideo] play video from local storage but always preload (Issue #451)




 
i have a problem with a local video, when me implement to my code just show preload like this
 

 
My code like this
 String title = "Video Player";
 String path = Environment.getExternalStorageDirectory().getAbsolutePath() + "/storage/emulated/0/Download/short.mp4";
 mVideoView.setUp(path, title);
 
and permission same like your demo
