### ISSUE TITLE
support m3u8 and example custom UI 

### ISSUE THREAD

**Issue by tusantrey2** [Jzvd/JiaoZiVideoPlayer#455]

**Comment by lipangit** [comment]
depends on mediaplayer&nbsp; youcan change mediaplayer&nbsp; .see custom mediaplayer



---Original---
From: ***@***.***&gt;
Date: Tue, Jun 28, 2022 17:56 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [Jzvd/JZVideo] support m3u8?  (Issue #455)

**Comment by tusantrey2** [comment]
> depends on mediaplayer&nbsp; youcan change mediaplayer&nbsp; .see custom mediaplayer
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Tue, Jun 28, 2022 17:56 PM To: ***@***.***&gt;; Cc: ***@***.***&gt;; Subject: [Jzvd/JZVideo] support m3u8? (Issue #455) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

**last question from me :**

how about custom UI? i still confuse about your demo. i hope next you make a wiki so can view more example from you. is not about demo apk but demo example from your github self.

and this issue will be closed.
