### ISSUE TITLE
Bug Start Video

### ISSUE THREAD

**Issue by LichKing255** [Jzvd/JiaoZiVideoPlayer#46]
There are two problems:
1. Loading speed of movie and its start is very slow.
2. After movie starts in 5 second, it stops.

**Comment by lipangit** [comment]
It depends on the Media engine   eg：android.media.MediaPlayer  ijkplayer  exoplayer

**Comment by LichKing255** [comment]
i use android.media.MediaPlayer, in older versions there was no such problem.

**Comment by lipangit** [comment]
witch version no problem  .  witch version have problem

**Comment by LichKing255** [comment]
> witch version no problem . witch version have problem

i update yesterday to last version. But problem is still there.

**Comment by lipangit** [comment]
what log， does it work well on demo?  I need more informaotation

**Comment by LichKing255** [comment]
now fixed.
