### ISSUE TITLE
自己编译后的ijkplayer怎么替换啊

### ISSUE THREAD

**Issue by aohanhongzhi** [Jzvd/JiaoZiVideoPlayer#498]
**需求描述

为了防止生成的ijkplayer库过大，默认的ijkplayer库的ffpmeg没有配置支持pcm_alaw的解码，不支持解码pcm_alaw的音频，导致声音播放不了。

![image](https://github.com/Jzvd/JZVideo/assets/37319319/b0c75f4e-82c4-49ae-834d-9bda0f066b15)
https://github.com/Bilibili/ijkplayer/issues/4559

因此必须自己编译ijkplayer，开启对pcm_alaw的支持，才能增加对pcm_alaw声音的解码，正常播放声音。

目前已经按照

https://blog.csdn.net/qq_24252589/article/details/130210512

https://zinyan.com/?p=260
https://dl.google.com/android/repository/android-ndk-r14b-linux-x86_64.zip

https://www.jianshu.com/p/21e4dd83beb3

自己编译完成了。

现在不知道这个生成的so文件，应该怎么替换到当前饺子框架里面去。

![image](https://github.com/Jzvd/JZVideo/assets/37319319/695d0fa8-87c0-40a3-9ef9-7183b0d3bf3e)

android工程

![image](https://github.com/Jzvd/JZVideo/assets/37319319/126a6e1c-7fc0-47cd-80de-8331a98e5f66)

# 具体参考文档

【腾讯文档】Android流媒体增加pcm_alaw格式音频解码
https://docs.qq.com/doc/DSHV5b25mQ01uZkpV

**Comment by lbchs5343** [comment]
so的调用是jk的jar包的事,饺子是调用了Java层api,只要你处理好jk的Java层调用so,并编译为aar 就可以使用libs形式引入aar,再根据饺子提供的统一调用jk的接口Java文件做出你对jkJava层api的相应修改,这样应该就可以了

**Comment by aohanhongzhi** [comment]
【腾讯文档】Android流媒体增加pcm_alaw格式音频解码
https://docs.qq.com/doc/DSHV5b25mQ01uZkpV
