### ISSUE TITLE
下载library

### ISSUE THREAD

**Issue by XuEnhao** [Jzvd/JiaoZiVideoPlayer#55]
**什么jzvd版本

**相关log是什么

**demo是否有这个问题

**如何操作复现

**什么安卓版本，什么机型

**最好有截图或者视频说明情况

**Comment by XuEnhao** [comment]
jz_fullscreen_id  jz_tiny_id 和这个找不到这个id。发现最新的library功能不如 远程仓库全 于是想把远程仓库的代码拷贝过去 找不到这两个id

**Comment by XuEnhao** [comment]
6.2.10 最新的没有了好多功能 你这个项目中最新的library 和这个6.2.10对比的话

**Comment by lipangit** [comment]
用新版本，然后拷贝对应版本的布局

**Comment by XuEnhao** [comment]
jz_fullscreen_id jz_tiny_id 和这个找不到这个id。 6.2.10 jzVideoPlayer中findViewId 这两个 
但是在布局中没有这两个 我拷贝过去代码 找不到id

**Comment by lipangit** [comment]
找你引用的对应的饺子版本，里面的资源



---原始邮件---
发件人: "XuEnhao"<notifications@github.com&gt;
发送时间: 2020年2月22日(周六) 上午10:28
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 下载library (#55)



jz_fullscreen_id jz_tiny_id 和这个找不到这个id。 6.2.10 jzVideoPlayer中findViewId 这两个
 但是在布局中没有这两个 我拷贝过去代码 找不到id
