### ISSUE TITLE
网络分段视频播放

### ISSUE THREAD

**Issue by mgr9525** [Jzvd/JiaoZiVideoPlayer#66]
**需求描述
有些视频被裁决成5分钟一段，但是要求在一起播放，而且需要一个加载超时的监听，用来更换token

**其他app是否实现
没有

**截图或者小视频说明

**Comment by lipangit** [comment]
是m3u8格式吗，这种放到播放内核中，内核会处理。如果手动处理的话比较复杂，修改较多



---原始邮件---
发件人: "Linsk Ruis"<notifications@github.com&gt;
发送时间: 2020年3月6日(周五) 下午2:48
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 网络分段视频播放 (#66)



**需求描述
 有些视频被裁决成5分钟一段，但是要求在一起播放，而且需要一个加载超时的监听，用来更换token
 
**其他app是否实现
 没有
 
**截图或者小视频说明

**Comment by mgr9525** [comment]
有些事mp4，有些事flv，m3u8也有额。。。

**Comment by lipangit** [comment]
为什么这么拆分视频



---原始邮件---
发件人: "Linsk Ruis"<notifications@github.com&gt;
发送时间: 2020年3月6日(周五) 下午2:56
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 网络分段视频播放 (#66)



有些事mp4，有些事flv，m3u8也有额。。。

**Comment by mgr9525** [comment]
说实话，是直接解析优酷的播放地址，所以是分段的

**Comment by lipangit** [comment]
难搞老铁



---原始邮件---
发件人: "Linsk Ruis"<notifications@github.com&gt;
发送时间: 2020年3月6日(周五) 下午5:10
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 网络分段视频播放 (#66)



说实话，是直接解析优酷的播放地址，所以是分段的

**Comment by mgr9525** [comment]
...
