### ISSUE TITLE
jzstd的preLoad和AndroidVideoCache这个库一起用，会消耗两倍流量吗

### ISSUE THREAD

**Issue by jerry9433** [Jzvd/JiaoZiVideoPlayer#71]
**需求描述
我是仿抖音列表，会用jzstd.startPreloading()方法预加载下一条，又重写了setUp方法，使用了videoCahceProxy的url，会有什么影响吗
**其他app是否实现

**截图或者小视频说明

**Comment by lipangit** [comment]
不会。preloading是mediaplayer prepare之后憋着不start，什么时候需要什么时候start。

**Comment by lipangit** [comment]
正常播放是直接调用start，preloading只是在需要的时候调用start

**Comment by jerry9433** [comment]
那会预加载视频数据吗

**Comment by lipangit** [comment]
会，但是不能release，release之后就没了
