### ISSUE TITLE
小屏状态下不显示标题，全屏模式下显示标题

### ISSUE THREAD

**Issue by MiracleChen001** [Jzvd/JiaoZiVideoPlayer#75]
老框架可以的，新框架里，按照以前方法在setup里设置，不起作用

`public class JzvdStdShowTitleAfterFullscreen extends JzvdStd {
    public JzvdStdShowTitleAfterFullscreen(Context context) {
        super(context);
    }

    public JzvdStdShowTitleAfterFullscreen(Context context, AttributeSet attrs) {
        super(context, attrs);
    }

    @Override
    public void setUp(JZDataSource jzDataSource, int screen) {
        super.setUp(jzDataSource, screen);
        if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {
            titleTextView.setVisibility(View.VISIBLE);
        } else {
            titleTextView.setVisibility(View.INVISIBLE);
        }
    }
}
`

**Comment by lipangit** [comment]
demo中smallchangeuiactivity有例子&nbsp; 饺子想摇头，非全屏没有标题，全屏有标题，亲测功能正常，参考demo使用。





---原始邮件---
发件人: "MiracleChen001"<notifications@github.com&gt;
发送时间: 2020年3月17日(周二) 下午5:06
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 小屏状态下不显示标题，全屏模式下显示标题 (#75)




 
老框架可以的，新框架里，按照以前方法在setup里设置，不起作用
 
`public class JzvdStdShowTitleAfterFullscreen extends JzvdStd {
 public JzvdStdShowTitleAfterFullscreen(Context context) {
 super(context);
 }
 public JzvdStdShowTitleAfterFullscreen(Context context, AttributeSet attrs) {     super(context, attrs); } @Override public void setUp(JZDataSource jzDataSource, int screen) {     super.setUp(jzDataSource, screen);     if (currentScreen == SCREEN_WINDOW_FULLSCREEN) {         titleTextView.setVisibility(View.VISIBLE);     } else {         titleTextView.setVisibility(View.INVISIBLE);     } }  
}
 `

**Comment by MiracleChen001** [comment]
感谢回复，Api变了，参考demo可用。
