### ISSUE TITLE
切换到全屏时，cloneAJzvd(vg) 能否去掉？

### ISSUE THREAD

**Issue by tudou0digua** [Jzvd/JiaoZiVideoPlayer#78]
**需求描述
在Jzvd parent的高度为固定高度时，gotoScreenFullscreen()方法中的，cloneAJzvd(vg) 能否去掉？
大致看了下，切换到全屏时，getParent() 中add clone后的 Jzvd，貌似没啥作用？
请问下，设计clone的目的是？

**Comment by lipangit** [comment]
在列表中，如果进入全屏之后因为非正常原因退出全屏，列表中原来的位置就是空白的什么都没有，为了能让列表继续正常工作就克隆了一个占位置。



---原始邮件---
发件人: "tudou0digua"<notifications@github.com&gt;
发送时间: 2020年3月18日(周三) 晚上8:23
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 切换到全屏时，cloneAJzvd(vg) 能否去掉？ (#78)




 
**需求描述
 在Jzvd parent的高度为固定高度时，gotoScreenFullscreen()方法中的，cloneAJzvd(vg) 能否去掉？
 大致看了下，切换到全屏时，getParent() 中add clone后的 Jzvd，貌似没啥作用？
 请问下，设计clone的目的是？

**Comment by lipangit** [comment]
你的需求是什么有没有思路解决，我给你提供思路。



---原始邮件---
发件人: "tudou0digua"<notifications@github.com&gt;
发送时间: 2020年3月18日(周三) 晚上8:23
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 切换到全屏时，cloneAJzvd(vg) 能否去掉？ (#78)




 
**需求描述
 在Jzvd parent的高度为固定高度时，gotoScreenFullscreen()方法中的，cloneAJzvd(vg) 能否去掉？
 大致看了下，切换到全屏时，getParent() 中add clone后的 Jzvd，貌似没啥作用？
 请问下，设计clone的目的是？

**Comment by tudou0digua** [comment]
原来如此

**Comment by JarvisBuop** [comment]
原来如此,受教了
