### ISSUE TITLE
全屏时报错。。

### ISSUE THREAD

**Issue by xuzh2017** [Jzvd/JiaoZiVideoPlayer#79]
**什么jzvd版本
7.2.2
**相关log是什么

**demo是否有这个问题

**自己做了哪些修改
我用的28.0.3版本
**如何操作复现
点击全屏时候会闪退。引入的lib里AppCompatActivity报红
**什么安卓版本，什么机型

**截图或者视频说明情况
![Y_FK_GF A})M8ZR @3478{2](https://user-images.githubusercontent.com/28645348/77132742-637f8c80-6a9b-11ea-9020-29be7e2e01ee.png)
![Z3}6 MNVNW8~A2I6@{5RX_R](https://user-images.githubusercontent.com/28645348/77132769-7d20d400-6a9b-11ea-8cb7-8913c3eccfb2.png)

**Comment by lipangit** [comment]
编译不通过是怎么运行的。环境的问题。



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 中午11:12
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79)




 
**什么jzvd版本
 7.2.2
 **相关log是什么
 
**demo是否有这个问题
 
**自己做了哪些修改
 我用的28.0.3版本
 **如何操作复现
 点击全屏时候会闪退。引入的lib里AppCompatActivity报红
 **什么安卓版本，什么机型
 
**截图或者视频说明情况

**Comment by xuzh2017** [comment]
> 编译不通过是怎么运行的。环境的问题。
> […](#)
> ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年3月20日(周五) 中午11:12 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79) **什么jzvd版本 7.2.2 **相关log是什么 **demo是否有这个问题 **自己做了哪些修改 我用的28.0.3版本 **如何操作复现 点击全屏时候会闪退。引入的lib里AppCompatActivity报红 **什么安卓版本，什么机型 **截图或者视频说明情况 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

编译通过了。这是implemention 引入的jz库。只有运行点击全屏的时候会闪退。。报这个错

**Comment by xuzh2017** [comment]
是必须升级到AndroidX 吗？

**Comment by lipangit** [comment]
你提的问题必须重视，现在用新版饺子必须升级androidx。下一步应该在library中删除androidx让饺子适配更多项目。



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 下午2:42
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79)




 
是必须升级到AndroidX 吗？

**Comment by lipangit** [comment]
告诉你个好消息。最新的develop分支的library已经干掉androidx了，最晚下周一能用了。



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 下午2:42
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79)




 
是必须升级到AndroidX 吗？

**Comment by xuzh2017** [comment]
辛苦楼主了。。感谢感谢

**Comment by xuzh2017** [comment]
![TIM截图20200320175333](https://user-images.githubusercontent.com/28645348/77152879-c1c86180-6ad3-11ea-9a9b-10a1a1592c7c.png)
还有个问题大佬。这个wifi监听老是报错怎么回事。

**Comment by xuzh2017** [comment]
![20200320175333](https://user-images.githubusercontent.com/28645348/77152986-e9b7c500-6ad3-11ea-8177-f916def05d59.png)

还有个问题大佬。这个wifi监听老是报错怎么回事。

**Comment by xuzh2017** [comment]
> 告诉你个好消息。最新的develop分支的library已经干掉androidx了，最晚下周一能用了。
> […](#)
> ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年3月20日(周五) 下午2:42 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79) 是必须升级到AndroidX 吗？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

![20200320175333](https://user-images.githubusercontent.com/28645348/77153064-0b18b100-6ad4-11ea-8411-b2d5c9fa3a39.png)
还有个问题大佬。这个wifi监听老是报错怎么回事。

**Comment by lipangit** [comment]
什么情况下会复现，你有啥想法吗



---原始邮件---
发件人: "xuzh2017"<notifications@github.com&gt;
发送时间: 2020年3月20日(周五) 下午5:54
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;;
主题: Re: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79)




 

 还有个问题大佬。这个wifi监听老是报错怎么回事。

**Comment by xuzh2017** [comment]
> 什么情况下会复现，你有啥想法吗
> […](#)
> ---原始邮件--- 发件人: "xuzh2017"<notifications@github.com&gt; 发送时间: 2020年3月20日(周五) 下午5:54 收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;; 抄送: "Comment"<comment@noreply.github.com&gt;;"Nathen"<1066666651@qq.com&gt;; 主题: Re: [Jzvd/JiaoZiVideoPlayer] 全屏时报错。。 (#79) 还有个问题大佬。这个wifi监听老是报错怎么回事。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感觉就是releaseallvideos释放后再走goonresume方法会出现，做次判断就行。。
