### ISSUE TITLE
Autoplay?

### ISSUE THREAD

**Issue by froozeapp** [Jzvd/JiaoZiVideoPlayer#92]
Is there any way to create Autoplay as soon as the video is in the screen? Recyclerview.

**Comment by lipangit** [comment]
jzvd.startvideo()



---Original---

**Comment by froozeapp** [comment]
This doesn't work in recylcerview. It just plays the 1st Video. How did you do it in your TikTok example?

**Comment by lipangit** [comment]
Learn source code please .  I do not know.

**Comment by froozeapp** [comment]
Ok, thanks I'll take a look at it.
