### ISSUE TITLE
有大佬封装成rn插件吗?

### ISSUE THREAD

**Issue by 23233** [Jzvd/JiaoZiVideoPlayer#97]
### 想问问 有没有这种打算呢?

**Comment by lipangit** [comment]
这个靠你们了，岁是我找我



---原始邮件---
发件人: "23233"<notifications@github.com&gt;
发送时间: 2020年4月5日(周日) 中午12:59
收件人: "Jzvd/JiaoZiVideoPlayer"<JiaoZiVideoPlayer@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [Jzvd/JiaoZiVideoPlayer] 有大佬封装成rn插件吗? (#97)




 
我在之前的github issue上看到很多实用rn封装的 但是似乎没人开放出来?
 
想问问 有没有这种打算呢?
